[2023-04-04T14:35:13.449683+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T14:35:30.261236+0300] [DEBUG] [logging.py:11]  Received message [AQID:4264] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-04T14:35:39.235310+0300] [DEBUG] [logging.py:11]  Received message [AQID:4266] from user [ID:448470724] in chat [ID:448470724] text "Task today"
[2023-04-04T14:35:45.735041+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:4"] from user [ID:448470724] for message [ID:4267] in chat [ID:448470724]
[2023-04-04T14:36:04.254494+0300] [DEBUG] [logging.py:11]  Received message [AQID:4270] from user [ID:448470724] in chat [ID:448470724] text "14:37"
[2023-04-04T14:36:07.633541+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4271] in chat [ID:448470724]
[2023-04-04T14:36:27.708050+0300] [DEBUG] [logging.py:11]  Received message [AQID:4275] from user [ID:448470724] in chat [ID:448470724] text "Time cases"
[2023-04-04T14:37:04.872956+0300] [DEBUG] [logging.py:11]  Received message [AQID:4277] from user [ID:448470724] in chat [ID:448470724] text "Time cases"
[2023-04-04T14:58:23.465613+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T14:58:31.775799+0300] [DEBUG] [logging.py:11]  Received message [AQID:4280] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-04T15:06:21.276747+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T15:06:23.754311+0300] [DEBUG] [logging.py:11]  Received message [AQID:4283] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-04T15:11:32.901274+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T15:11:37.617241+0300] [DEBUG] [logging.py:11]  Received message [AQID:4286] from user [ID:448470724] in chat [ID:448470724] text "Completed cases üèÜ"
[2023-04-04T15:25:13.958949+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T15:25:19.197248+0300] [DEBUG] [logging.py:11]  Received message [AQID:4289] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-04T15:25:21.754683+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_to_do_5"] from user [ID:448470724] for message [ID:4291] in chat [ID:448470724]
[2023-04-04T18:30:58.059463+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T18:33:16.868119+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T18:33:32.916526+0300] [DEBUG] [logging.py:11]  Received message [AQID:4293] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-04T18:33:45.317337+0300] [DEBUG] [logging.py:11]  Received message [AQID:4295] from user [ID:448470724] in chat [ID:448470724] text "Task today time 1"
[2023-04-04T18:33:51.166459+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:4"] from user [ID:448470724] for message [ID:4296] in chat [ID:448470724]
[2023-04-04T18:34:06.055142+0300] [DEBUG] [logging.py:11]  Received message [AQID:4299] from user [ID:448470724] in chat [ID:448470724] text "18:35"
[2023-04-04T18:34:08.733310+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4300] in chat [ID:448470724]
[2023-04-04T18:37:19.907897+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T18:37:49.953137+0300] [DEBUG] [logging.py:11]  Received message [AQID:4304] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-04T18:37:58.802936+0300] [DEBUG] [logging.py:11]  Received message [AQID:4306] from user [ID:448470724] in chat [ID:448470724] text "task today time 2"
[2023-04-04T18:38:01.729639+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:4"] from user [ID:448470724] for message [ID:4307] in chat [ID:448470724]
[2023-04-04T18:38:08.672054+0300] [DEBUG] [logging.py:11]  Received message [AQID:4310] from user [ID:448470724] in chat [ID:448470724] text "18:29"
[2023-04-04T18:38:15.945102+0300] [DEBUG] [logging.py:11]  Received message [AQID:4312] from user [ID:448470724] in chat [ID:448470724] text "18:39"
[2023-04-04T18:38:17.729555+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4313] in chat [ID:448470724]
[2023-04-04T18:41:51.079937+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T18:42:06.972081+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T18:43:23.258958+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T18:44:50.533830+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T18:45:22.974700+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T18:52:11.358584+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T18:52:24.794133+0300] [DEBUG] [logging.py:11]  Received message [AQID:4317] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-04T18:52:33.551232+0300] [DEBUG] [logging.py:11]  Received message [AQID:4319] from user [ID:448470724] in chat [ID:448470724] text "Task check notify"
[2023-04-04T18:52:38.754398+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:4"] from user [ID:448470724] for message [ID:4320] in chat [ID:448470724]
[2023-04-04T18:52:45.652441+0300] [DEBUG] [logging.py:11]  Received message [AQID:4323] from user [ID:448470724] in chat [ID:448470724] text "18:53"
[2023-04-04T18:52:48.792025+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4324] in chat [ID:448470724]
[2023-04-04T19:38:09.823689+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T19:38:23.941231+0300] [DEBUG] [logging.py:11]  Received message [AQID:4328] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-04T19:38:33.761538+0300] [DEBUG] [logging.py:11]  Received message [AQID:4330] from user [ID:448470724] in chat [ID:448470724] text "Today check time"
[2023-04-04T19:38:35.776677+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:4"] from user [ID:448470724] for message [ID:4331] in chat [ID:448470724]
[2023-04-04T19:38:42.511694+0300] [DEBUG] [logging.py:11]  Received message [AQID:4334] from user [ID:448470724] in chat [ID:448470724] text "19:39"
[2023-04-04T19:38:44.473858+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4335] in chat [ID:448470724]
[2023-04-04T19:41:18.876920+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T19:41:28.824261+0300] [DEBUG] [logging.py:11]  Received message [AQID:4339] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-04T19:41:33.870190+0300] [DEBUG] [logging.py:11]  Received message [AQID:4341] from user [ID:448470724] in chat [ID:448470724] text "Task notify"
[2023-04-04T19:41:35.801317+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:4"] from user [ID:448470724] for message [ID:4342] in chat [ID:448470724]
[2023-04-04T19:41:41.054749+0300] [DEBUG] [logging.py:11]  Received message [AQID:4345] from user [ID:448470724] in chat [ID:448470724] text "19:42"
[2023-04-04T19:41:43.258873+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4346] in chat [ID:448470724]
[2023-04-04T19:53:59.198171+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T19:54:10.362985+0300] [DEBUG] [logging.py:11]  Received message [AQID:4350] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-04T19:54:18.744334+0300] [DEBUG] [logging.py:11]  Received message [AQID:4352] from user [ID:448470724] in chat [ID:448470724] text "Task check notify 2"
[2023-04-04T19:54:21.867284+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:4"] from user [ID:448470724] for message [ID:4353] in chat [ID:448470724]
[2023-04-04T19:54:27.024029+0300] [DEBUG] [logging.py:11]  Received message [AQID:4356] from user [ID:448470724] in chat [ID:448470724] text "19:55"
[2023-04-04T19:54:28.789733+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4357] in chat [ID:448470724]
[2023-04-04T19:58:12.721805+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T19:58:18.656301+0300] [DEBUG] [logging.py:11]  Received message [AQID:4361] from user [ID:448470724] in chat [ID:448470724] text "/new_task"
[2023-04-04T19:58:26.747142+0300] [DEBUG] [logging.py:11]  Received message [AQID:4363] from user [ID:448470724] in chat [ID:448470724] text "Task check notify 3"
[2023-04-04T19:58:28.870896+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:4"] from user [ID:448470724] for message [ID:4364] in chat [ID:448470724]
[2023-04-04T19:58:35.762675+0300] [DEBUG] [logging.py:11]  Received message [AQID:4367] from user [ID:448470724] in chat [ID:448470724] text "19:59"
[2023-04-04T19:58:38.410839+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4368] in chat [ID:448470724]
[2023-04-04T20:02:18.405440+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T20:02:29.851354+0300] [DEBUG] [logging.py:11]  Received message [AQID:4372] from user [ID:448470724] in chat [ID:448470724] text "/new_task"
[2023-04-04T20:02:40.950078+0300] [DEBUG] [logging.py:11]  Received message [AQID:4374] from user [ID:448470724] in chat [ID:448470724] text "task check notify 4"
[2023-04-04T20:02:43.165382+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:4"] from user [ID:448470724] for message [ID:4375] in chat [ID:448470724]
[2023-04-04T20:02:50.439363+0300] [DEBUG] [logging.py:11]  Received message [AQID:4378] from user [ID:448470724] in chat [ID:448470724] text "20:03"
[2023-04-04T20:02:51.908477+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4379] in chat [ID:448470724]
[2023-04-04T20:12:12.757765+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T20:13:22.406477+0300] [DEBUG] [logging.py:11]  Received message [AQID:4384] from user [ID:448470724] in chat [ID:448470724] text "/new_task"
[2023-04-04T20:13:39.665370+0300] [DEBUG] [logging.py:11]  Received message [AQID:4386] from user [ID:448470724] in chat [ID:448470724] text "Task check periodicity"
[2023-04-04T20:13:42.899692+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:4"] from user [ID:448470724] for message [ID:4387] in chat [ID:448470724]
[2023-04-04T20:14:12.338695+0300] [DEBUG] [logging.py:11]  Received message [AQID:4390] from user [ID:448470724] in chat [ID:448470724] text "20:15"
[2023-04-04T20:14:14.017400+0300] [DEBUG] [logging.py:19]  Received callback query [data:"yes"] from user [ID:448470724] for message [ID:4391] in chat [ID:448470724]
[2023-04-04T20:14:16.817164+0300] [DEBUG] [logging.py:11]  Received message [AQID:4393] from user [ID:448470724] in chat [ID:448470724] text "1d"
[2023-04-04T20:18:51.973194+0300] [INFO] [main.py:15]  Bot startup
[2023-04-04T20:19:00.240257+0300] [DEBUG] [logging.py:11]  Received message [AQID:4397] from user [ID:448470724] in chat [ID:448470724] text "/new_task"
[2023-04-04T20:19:13.660016+0300] [DEBUG] [logging.py:11]  Received message [AQID:4399] from user [ID:448470724] in chat [ID:448470724] text "Task check notify periodicity 2"
[2023-04-04T20:19:15.577382+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:4"] from user [ID:448470724] for message [ID:4400] in chat [ID:448470724]
[2023-04-04T20:19:20.999987+0300] [DEBUG] [logging.py:11]  Received message [AQID:4403] from user [ID:448470724] in chat [ID:448470724] text "20:20"
[2023-04-04T20:19:23.606194+0300] [DEBUG] [logging.py:19]  Received callback query [data:"yes"] from user [ID:448470724] for message [ID:4404] in chat [ID:448470724]
[2023-04-04T20:19:25.445976+0300] [DEBUG] [logging.py:11]  Received message [AQID:4406] from user [ID:448470724] in chat [ID:448470724] text "1d"
[2023-04-04T20:21:49.889847+0300] [DEBUG] [logging.py:19]  Received callback query [data:"is_done_task_28"] from user [ID:448470724] for message [ID:4409] in chat [ID:448470724]
[2023-04-06T09:44:44.623175+0300] [INFO] [main.py:15]  Bot startup
[2023-04-06T09:44:56.107538+0300] [DEBUG] [logging.py:11]  Received message [AQID:4413] from user [ID:448470724] in chat [ID:448470724] text "/start"
[2023-04-06T09:45:31.213179+0300] [INFO] [main.py:15]  Bot startup
[2023-04-06T09:47:19.013753+0300] [INFO] [main.py:15]  Bot startup
[2023-04-06T09:48:00.409802+0300] [INFO] [main.py:15]  Bot startup
[2023-04-06T09:48:06.242894+0300] [DEBUG] [logging.py:11]  Received message [AQID:4417] from user [ID:448470724] in chat [ID:448470724] text "/start"
[2023-04-06T09:48:08.123217+0300] [DEBUG] [logging.py:19]  Received callback query [data:"lang_en"] from user [ID:448470724] for message [ID:4418] in chat [ID:448470724]
[2023-04-06T09:48:09.396314+0300] [DEBUG] [logging.py:11]  Received message [AQID:4420] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-06T09:48:17.103887+0300] [DEBUG] [logging.py:11]  Received message [AQID:4422] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-06T19:55:57.715005+0300] [INFO] [main.py:15]  Bot startup
[2023-04-06T19:56:07.522262+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178918864, "message": {"message_id": 4425, "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680810968, "text": "To-do list üìÉ"}} 
Traceback (most recent call last):
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3173, in connect
    self._state.set_connection(self._connect())
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3913, in _connect
    conn = psycopg2.connect(**params)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3235, in execute_sql
    cursor = self.cursor(commit)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3219, in cursor
    self.connect()
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3172, in connect
    with __exception_wrapper__:
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3173, in connect
    self._state.set_connection(self._connect())
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3913, in _connect
    conn = psycopg2.connect(**params)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
peewee.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 108, in notify
    data.update(await check_filters(handler_obj.filters, args))
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\filters\filters.py", line 77, in check_filters
    f = await execute_filter(filter_, args)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\filters\filters.py", line 61, in execute_filter
    return await filter_.filter(*args, **filter_.kwargs)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\filters\filters.py", line 166, in __call__
    return await self.check(*args)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\filters\admin.py", line 14, in check
    message['database_user'] = get_user(message.from_user.id)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\services\users.py", line 19, in get_user
    return User.get_or_none(User.id == id)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 6629, in get_or_none
    return cls.get(*query, **filters)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 6624, in get
    return sq.get()
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 7072, in get
    return clone.execute(database)[0]
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 1962, in inner
    return method(self, database, *args, **kwargs)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 2033, in execute
    return self._execute(database)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 2206, in _execute
    cursor = database.execute(self)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3250, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3234, in execute_sql
    with __exception_wrapper__:
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3235, in execute_sql
    cursor = self.cursor(commit)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3219, in cursor
    self.connect()
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3172, in connect
    with __exception_wrapper__:
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3173, in connect
    self._state.set_connection(self._connect())
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\peewee.py", line 3913, in _connect
    conn = psycopg2.connect(**params)
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
peewee.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?


NoneType: None
[2023-04-06T19:58:51.560960+0300] [INFO] [main.py:15]  Bot startup
[2023-04-06T19:59:09.034464+0300] [DEBUG] [logging.py:11]  Received message [AQID:4427] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-06T20:49:13.959307+0300] [INFO] [main.py:15]  Bot startup
[2023-04-06T20:49:19.653177+0300] [DEBUG] [logging.py:11]  Received message [AQID:4429] from user [ID:448470724] in chat [ID:448470724] text "Help üÜò"
[2023-04-06T20:49:24.072009+0300] [DEBUG] [logging.py:11]  Received message [AQID:4431] from user [ID:448470724] in chat [ID:448470724] text "Completed cases üèÜ"
[2023-04-07T10:46:51.744265+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T10:46:57.393882+0300] [DEBUG] [logging.py:11]  Received message [AQID:4482] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-07T17:10:31.699343+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T17:10:39.930301+0300] [DEBUG] [logging.py:11]  Received message [AQID:4485] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-07T17:10:43.344201+0300] [DEBUG] [logging.py:11]  Received message [AQID:4487] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T17:10:53.673372+0300] [DEBUG] [logging.py:11]  Received message [AQID:4489] from user [ID:448470724] in chat [ID:448470724] text "Task 1"
[2023-04-07T17:10:58.418294+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:12"] from user [ID:448470724] for message [ID:4490] in chat [ID:448470724]
[2023-04-07T17:11:03.497195+0300] [DEBUG] [logging.py:11]  Received message [AQID:4493] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T17:11:05.937129+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4494] in chat [ID:448470724]
[2023-04-07T17:26:57.193164+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T17:27:12.249929+0300] [DEBUG] [logging.py:11]  Received message [AQID:4497] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T17:27:16.341046+0300] [DEBUG] [logging.py:11]  Received message [AQID:4499] from user [ID:448470724] in chat [ID:448470724] text "Task 1"
[2023-04-07T17:27:18.404596+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:13"] from user [ID:448470724] for message [ID:4500] in chat [ID:448470724]
[2023-04-07T17:27:22.766020+0300] [DEBUG] [logging.py:11]  Received message [AQID:4503] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T17:27:25.352652+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4504] in chat [ID:448470724]
[2023-04-07T17:27:25.651256+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178918907, "callback_query": {"id": "1926167096780999701", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4504, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680888449, "text": "Do you want to set a periodicity?", "reply_markup": {"inline_keyboard": [[{"text": "No", "callback_data": "no"}], [{"text": "Yes", "callback_data": "yes"}]]}}, "chat_instance": "1646365164926244667", "data": "no"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 69, in _process_periodicity
    await callback_query.answer("Do you want to add files?", reply_markup=get_add_file_inline_markup())
TypeError: CallbackQuery.answer() got an unexpected keyword argument 'reply_markup'

NoneType: None
[2023-04-07T17:29:29.660366+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T17:29:44.484906+0300] [DEBUG] [logging.py:11]  Received message [AQID:4507] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T17:29:48.236089+0300] [DEBUG] [logging.py:11]  Received message [AQID:4509] from user [ID:448470724] in chat [ID:448470724] text "Task 1"
[2023-04-07T17:29:51.067242+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:12"] from user [ID:448470724] for message [ID:4510] in chat [ID:448470724]
[2023-04-07T17:29:54.932607+0300] [DEBUG] [logging.py:11]  Received message [AQID:4513] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T17:29:57.684340+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4514] in chat [ID:448470724]
[2023-04-07T17:30:05.192998+0300] [DEBUG] [logging.py:19]  Received callback query [data:"finish-adding"] from user [ID:448470724] for message [ID:4516] in chat [ID:448470724]
[2023-04-07T17:30:05.395828+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178918913, "callback_query": {"id": "1926167094782746655", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4516, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680888605, "text": "Do you want to add files?", "reply_markup": {"inline_keyboard": [[{"text": "No", "callback_data": "finish-adding"}], [{"text": "Yes", "callback_data": "start-adding"}]]}}, "chat_instance": "1646365164926244667", "data": "finish-adding"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 105, in _process_attachments
    data['attachments'] += ''
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\storage.py", line 439, in __getitem__
    return self._data[item]
KeyError: 'attachments'

NoneType: None
[2023-04-07T17:55:12.462090+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T17:55:17.496309+0300] [DEBUG] [logging.py:11]  Received message [AQID:4519] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T17:55:26.237688+0300] [DEBUG] [logging.py:11]  Received message [AQID:4521] from user [ID:448470724] in chat [ID:448470724] text "Task 1"
[2023-04-07T17:55:28.762989+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:12"] from user [ID:448470724] for message [ID:4522] in chat [ID:448470724]
[2023-04-07T17:56:10.000370+0300] [DEBUG] [logging.py:11]  Received message [AQID:4525] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T17:56:12.797555+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4526] in chat [ID:448470724]
[2023-04-07T17:56:17.711137+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4528] in chat [ID:448470724]
[2023-04-07T17:57:47.245645+0300] [DEBUG] [logging.py:11]  Received message [AQID:4532] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T17:57:54.399624+0300] [DEBUG] [logging.py:11]  Received message [AQID:4534] from user [ID:448470724] in chat [ID:448470724] text "Task 2"
[2023-04-07T17:57:56.945446+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:12"] from user [ID:448470724] for message [ID:4535] in chat [ID:448470724]
[2023-04-07T17:58:01.389282+0300] [DEBUG] [logging.py:11]  Received message [AQID:4538] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T17:58:03.896906+0300] [DEBUG] [logging.py:19]  Received callback query [data:"yes"] from user [ID:448470724] for message [ID:4539] in chat [ID:448470724]
[2023-04-07T17:58:07.174491+0300] [DEBUG] [logging.py:11]  Received message [AQID:4541] from user [ID:448470724] in chat [ID:448470724] text "1d"
[2023-04-07T17:58:10.763498+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4542] in chat [ID:448470724]
[2023-04-07T17:58:20.709219+0300] [DEBUG] [logging.py:11]  Received message [AQID:4546] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T17:58:24.149395+0300] [DEBUG] [logging.py:11]  Received message [AQID:4548] from user [ID:448470724] in chat [ID:448470724] text "Task 3"
[2023-04-07T17:58:26.536706+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:12"] from user [ID:448470724] for message [ID:4549] in chat [ID:448470724]
[2023-04-07T17:58:31.058823+0300] [DEBUG] [logging.py:11]  Received message [AQID:4552] from user [ID:448470724] in chat [ID:448470724] text "14:00"
[2023-04-07T17:58:41.683960+0300] [DEBUG] [logging.py:19]  Received callback query [data:"yes"] from user [ID:448470724] for message [ID:4553] in chat [ID:448470724]
[2023-04-07T17:58:50.110000+0300] [DEBUG] [logging.py:11]  Received message [AQID:4555] from user [ID:448470724] in chat [ID:448470724] text "1d"
[2023-04-07T17:58:56.503195+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4556] in chat [ID:448470724]
[2023-04-07T17:59:14.864397+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178918934, "message": {"message_id": 4558, "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680890361, "document": {"file_name": "UNIT 1.docx", "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "file_id": "BQACAgIAAxkBAAIRzmQwL8k3ZdCUvfTOY3DK-BhmvGwUAAJcMAAC0DuISeoNIs2DBXNiLwQ", "file_unique_id": "AgADXDAAAtA7iEk", "file_size": 17766}}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 135, in _process_attachments_files
    data["attachments"] += f"{filename},{file_type};"
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\storage.py", line 439, in __getitem__
    return self._data[item]
KeyError: 'attachments'

NoneType: None
[2023-04-07T18:03:32.800873+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T18:03:41.831831+0300] [DEBUG] [logging.py:11]  Received message [AQID:4560] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T18:03:45.628688+0300] [DEBUG] [logging.py:11]  Received message [AQID:4562] from user [ID:448470724] in chat [ID:448470724] text "Task 3"
[2023-04-07T18:03:48.291514+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:19"] from user [ID:448470724] for message [ID:4563] in chat [ID:448470724]
[2023-04-07T18:03:53.410683+0300] [DEBUG] [logging.py:11]  Received message [AQID:4566] from user [ID:448470724] in chat [ID:448470724] text "17:00"
[2023-04-07T18:03:55.753720+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4567] in chat [ID:448470724]
[2023-04-07T18:03:59.032264+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4569] in chat [ID:448470724]
[2023-04-07T18:04:49.185605+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178918941, "message": {"message_id": 4571, "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680890696, "document": {"file_name": "coursework_opt_methods.pdf", "mime_type": "application/pdf", "thumbnail": {"file_id": "AAMCAgADGQEAAhHbZDAxF3sGx5P2CdS2-mH8zxm42ggAAmIwAALQO4hJNckCqsotpnwBAAdtAAMvBA", "file_unique_id": "AQADYjAAAtA7iEly", "file_size": 5751, "width": 226, "height": 320}, "thumb": {"file_id": "AAMCAgADGQEAAhHbZDAxF3sGx5P2CdS2-mH8zxm42ggAAmIwAALQO4hJNckCqsotpnwBAAdtAAMvBA", "file_unique_id": "AQADYjAAAtA7iEly", "file_size": 5751, "width": 226, "height": 320}, "file_id": "BQACAgIAAxkBAAIR22QwMRd7BseT9gnUtvph_M8ZuNoIAAJiMAAC0DuISTXJAqrKLaZ8LwQ", "file_unique_id": "AgADYjAAAtA7iEk", "file_size": 996302}, "caption": "att3"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 135, in _process_attachments_files
    data["attachments"] += f"{filename},{file_type};"
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\storage.py", line 439, in __getitem__
    return self._data[item]
KeyError: 'attachments'

NoneType: None
[2023-04-07T18:14:14.812382+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T18:14:44.537054+0300] [DEBUG] [logging.py:11]  Received message [AQID:4573] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T18:14:49.595808+0300] [DEBUG] [logging.py:11]  Received message [AQID:4575] from user [ID:448470724] in chat [ID:448470724] text "Task 3"
[2023-04-07T18:14:55.242168+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:8"] from user [ID:448470724] for message [ID:4576] in chat [ID:448470724]
[2023-04-07T18:15:00.821129+0300] [DEBUG] [logging.py:11]  Received message [AQID:4579] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T18:15:10.863560+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4580] in chat [ID:448470724]
[2023-04-07T18:15:12.747576+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4582] in chat [ID:448470724]
[2023-04-07T18:15:42.856739+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4585] in chat [ID:448470724]
[2023-04-07T18:22:35.575160+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T18:22:54.005151+0300] [DEBUG] [logging.py:11]  Received message [AQID:4590] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T18:22:58.848105+0300] [DEBUG] [logging.py:11]  Received message [AQID:4592] from user [ID:448470724] in chat [ID:448470724] text "Task 4"
[2023-04-07T18:23:11.832727+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:14"] from user [ID:448470724] for message [ID:4593] in chat [ID:448470724]
[2023-04-07T18:23:19.301703+0300] [DEBUG] [logging.py:11]  Received message [AQID:4596] from user [ID:448470724] in chat [ID:448470724] text "13:00"
[2023-04-07T18:23:22.914340+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4597] in chat [ID:448470724]
[2023-04-07T18:23:30.869918+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4599] in chat [ID:448470724]
[2023-04-07T18:24:25.273164+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4604] in chat [ID:448470724]
[2023-04-07T18:36:33.321161+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T18:36:53.432064+0300] [DEBUG] [logging.py:11]  Received message [AQID:4609] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-07T18:37:04.800328+0300] [DEBUG] [logging.py:11]  Received message [AQID:4610] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T18:37:10.750872+0300] [DEBUG] [logging.py:11]  Received message [AQID:4612] from user [ID:448470724] in chat [ID:448470724] text "Task 5"
[2023-04-07T18:37:12.945593+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:19"] from user [ID:448470724] for message [ID:4613] in chat [ID:448470724]
[2023-04-07T18:37:16.594183+0300] [DEBUG] [logging.py:11]  Received message [AQID:4616] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T18:37:18.744463+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4617] in chat [ID:448470724]
[2023-04-07T18:37:21.512711+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4619] in chat [ID:448470724]
[2023-04-07T18:37:46.280220+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4622] in chat [ID:448470724]
[2023-04-07T18:37:46.729554+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178918967, "callback_query": {"id": "1926167095387382523", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4622, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680892671, "text": "The file has been successfully uploaded.\nIf you don't want to upload any more files, click Finish.", "reply_markup": {"inline_keyboard": [[{"text": "Finish adding", "callback_data": "no-adding"}]]}}, "chat_instance": "1646365164926244667", "data": "no-adding"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 109, in _process_attachments
    await _view_task(await _save_task(callback_query.message, state, user, 'add'), 'add', '', callback_query.message)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 35, in _view_task
    await _view_files(task=task, response=response)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 72, in _view_files
    response += f"<a href='https://api.telegram.org/file/bot{bot.token}/{file['id']}'>üìÑ Document</a>\n"
NameError: name 'bot' is not defined

NoneType: None
[2023-04-07T18:39:41.058348+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T18:39:50.515959+0300] [DEBUG] [logging.py:11]  Received message [AQID:4626] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T18:39:58.712734+0300] [DEBUG] [logging.py:11]  Received message [AQID:4628] from user [ID:448470724] in chat [ID:448470724] text "Task 6"
[2023-04-07T18:40:00.831560+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:27"] from user [ID:448470724] for message [ID:4629] in chat [ID:448470724]
[2023-04-07T18:40:04.452734+0300] [DEBUG] [logging.py:11]  Received message [AQID:4632] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T18:40:08.960841+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4633] in chat [ID:448470724]
[2023-04-07T18:40:11.218619+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4635] in chat [ID:448470724]
[2023-04-07T18:40:30.080009+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4638] in chat [ID:448470724]
[2023-04-07T18:40:30.414053+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178918975, "callback_query": {"id": "1926167094907918620", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4638, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680892834, "text": "The file has been successfully uploaded.\nIf you don't want to upload any more files, click Finish.", "reply_markup": {"inline_keyboard": [[{"text": "Finish adding", "callback_data": "no-adding"}]]}}, "chat_instance": "1646365164926244667", "data": "no-adding"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 109, in _process_attachments
    await _view_task(await _save_task(callback_query.message, state, user, 'add'), 'add', '', callback_query.message, bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 35, in _view_task
    await _view_files(task=task, response=response)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 72, in _view_files
    response += f"<a href='https://api.telegram.org/file/bot{bot.token}/{file['id']}'>üìÑ Document</a>\n"
NameError: name 'bot' is not defined

NoneType: None
[2023-04-07T18:44:49.520431+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T18:44:55.436075+0300] [DEBUG] [logging.py:11]  Received message [AQID:4642] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T18:45:00.673862+0300] [DEBUG] [logging.py:11]  Received message [AQID:4644] from user [ID:448470724] in chat [ID:448470724] text "Task 7"
[2023-04-07T18:45:02.797986+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:19"] from user [ID:448470724] for message [ID:4645] in chat [ID:448470724]
[2023-04-07T18:45:06.098314+0300] [DEBUG] [logging.py:11]  Received message [AQID:4648] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T18:45:07.876468+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4649] in chat [ID:448470724]
[2023-04-07T18:45:10.117441+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4651] in chat [ID:448470724]
[2023-04-07T18:45:31.863151+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4654] in chat [ID:448470724]
[2023-04-07T18:45:32.151022+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178918983, "callback_query": {"id": "1926167094224490688", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4654, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680893136, "text": "The file has been successfully uploaded.\nIf you don't want to upload any more files, click Finish.", "reply_markup": {"inline_keyboard": [[{"text": "Finish adding", "callback_data": "no-adding"}]]}}, "chat_instance": "1646365164926244667", "data": "no-adding"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 109, in _process_attachments
    await _view_task(await _save_task(callback_query.message, state, user, 'add'), 'add', '', callback_query.message, bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 35, in _view_task
    await _view_files(task=task, response=response)
TypeError: _view_files() missing 1 required positional argument: 'bot'

NoneType: None
[2023-04-07T18:46:29.765528+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T18:46:37.365411+0300] [DEBUG] [logging.py:11]  Received message [AQID:4658] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T18:46:41.812149+0300] [DEBUG] [logging.py:11]  Received message [AQID:4660] from user [ID:448470724] in chat [ID:448470724] text "Task 8"
[2023-04-07T18:46:43.956928+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:20"] from user [ID:448470724] for message [ID:4661] in chat [ID:448470724]
[2023-04-07T18:46:47.677920+0300] [DEBUG] [logging.py:11]  Received message [AQID:4664] from user [ID:448470724] in chat [ID:448470724] text "21:00"
[2023-04-07T18:46:49.900438+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4665] in chat [ID:448470724]
[2023-04-07T18:46:51.650484+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4667] in chat [ID:448470724]
[2023-04-07T18:47:08.990031+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4670] in chat [ID:448470724]
[2023-04-07T18:47:09.308873+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178918991, "callback_query": {"id": "1926167096007999065", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4670, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680893233, "text": "The file has been successfully uploaded.\nIf you don't want to upload any more files, click Finish.", "reply_markup": {"inline_keyboard": [[{"text": "Finish adding", "callback_data": "no-adding"}]]}}, "chat_instance": "1646365164926244667", "data": "no-adding"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 109, in _process_attachments
    await _view_task(await _save_task(callback_query.message, state, user, 'add'), 'add', '', callback_query.message, bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 35, in _view_task
    await _view_files(task=task, response=response, bot=bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 72, in _view_files
    response += f"<a href='https://api.telegram.org/file/bot{bot.token}/{file['id']}'>üìÑ Document</a>\n"
AttributeError: 'Bot' object has no attribute 'token'

NoneType: None
[2023-04-07T18:47:55.879104+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T18:48:01.601147+0300] [DEBUG] [logging.py:11]  Received message [AQID:4674] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T18:48:05.348376+0300] [DEBUG] [logging.py:11]  Received message [AQID:4676] from user [ID:448470724] in chat [ID:448470724] text "Test task"
[2023-04-07T18:48:07.128032+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:27"] from user [ID:448470724] for message [ID:4677] in chat [ID:448470724]
[2023-04-07T18:48:11.137172+0300] [DEBUG] [logging.py:11]  Received message [AQID:4680] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T18:48:13.515022+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4681] in chat [ID:448470724]
[2023-04-07T18:48:16.253316+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4683] in chat [ID:448470724]
[2023-04-07T18:48:38.666846+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4686] in chat [ID:448470724]
[2023-04-07T18:48:38.949228+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178918999, "callback_query": {"id": "1926167093202816939", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4686, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680893323, "text": "The file has been successfully uploaded.\nIf you don't want to upload any more files, click Finish.", "reply_markup": {"inline_keyboard": [[{"text": "Finish adding", "callback_data": "no-adding"}]]}}, "chat_instance": "1646365164926244667", "data": "no-adding"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 109, in _process_attachments
    await _view_task(await _save_task(callback_query.message, state, user, 'add'), 'add', '', callback_query.message, bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 35, in _view_task
    await _view_files(task=task, response=response, bot=bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 72, in _view_files
    response += f"<a href='https://api.telegram.org/file/bot{bot.token}/{file['id']}'>üìÑ Document</a>\n"
AttributeError: 'Bot' object has no attribute 'token'

NoneType: None
[2023-04-07T18:53:44.423559+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T18:56:45.403930+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T18:56:55.577307+0300] [DEBUG] [logging.py:11]  Received message [AQID:4691] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-07T18:57:09.886028+0300] [DEBUG] [logging.py:11]  Received message [AQID:4692] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T18:57:20.764722+0300] [DEBUG] [logging.py:11]  Received message [AQID:4694] from user [ID:448470724] in chat [ID:448470724] text "test 1"
[2023-04-07T18:57:24.162696+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:13"] from user [ID:448470724] for message [ID:4695] in chat [ID:448470724]
[2023-04-07T18:57:27.917681+0300] [DEBUG] [logging.py:11]  Received message [AQID:4698] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T18:57:29.884219+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4699] in chat [ID:448470724]
[2023-04-07T18:57:31.928905+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4701] in chat [ID:448470724]
[2023-04-07T18:57:54.140680+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4704] in chat [ID:448470724]
[2023-04-07T18:57:55.817788+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919008, "callback_query": {"id": "1926167092997192045", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4704, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680893873, "text": "The file has been successfully uploaded.\nIf you don't want to upload any more files, click Finish.", "reply_markup": {"inline_keyboard": [[{"text": "Finish adding", "callback_data": "no-adding"}]]}}, "chat_instance": "1646365164926244667", "data": "no-adding"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 109, in _process_attachments
    await _view_task(await _save_task(callback_query.message, state, user, 'add'), 'add', '', callback_query.message, bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 36, in _view_task
    await _view_files(task=task, response=response, bot=bot)
TypeError: _view_files() got an unexpected keyword argument 'bot'

NoneType: None
[2023-04-07T18:58:44.644855+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T18:58:50.066035+0300] [DEBUG] [logging.py:11]  Received message [AQID:4708] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T18:58:53.503250+0300] [DEBUG] [logging.py:11]  Received message [AQID:4710] from user [ID:448470724] in chat [ID:448470724] text "test 2"
[2023-04-07T18:58:55.381403+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:13"] from user [ID:448470724] for message [ID:4711] in chat [ID:448470724]
[2023-04-07T18:58:59.676431+0300] [DEBUG] [logging.py:11]  Received message [AQID:4714] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T18:59:09.695074+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4715] in chat [ID:448470724]
[2023-04-07T18:59:15.735204+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4717] in chat [ID:448470724]
[2023-04-07T18:59:34.669645+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4720] in chat [ID:448470724]
[2023-04-07T18:59:35.306325+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919016, "callback_query": {"id": "1926167094857611162", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4720, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680893978, "text": "The file has been successfully uploaded.\nIf you don't want to upload any more files, click Finish.", "reply_markup": {"inline_keyboard": [[{"text": "Finish adding", "callback_data": "no-adding"}]]}}, "chat_instance": "1646365164926244667", "data": "no-adding"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 109, in _process_attachments
    await _view_task(await _save_task(callback_query.message, state, user, 'add'), 'add', '', callback_query.message, bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 36, in _view_task
    await _view_files(task=task, response=response)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 73, in _view_files
    response += f"<a href='https://api.telegram.org/file/bot{config.bot.token}/{file['id']}'>üìÑ Document</a>\n"
AttributeError: module 'data.config' has no attribute 'bot'

NoneType: None
[2023-04-07T19:01:39.093885+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T19:01:58.281405+0300] [DEBUG] [logging.py:11]  Received message [AQID:4725] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T19:02:02.374936+0300] [DEBUG] [logging.py:11]  Received message [AQID:4727] from user [ID:448470724] in chat [ID:448470724] text "test 3"
[2023-04-07T19:02:10.766597+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:12"] from user [ID:448470724] for message [ID:4728] in chat [ID:448470724]
[2023-04-07T19:02:14.210964+0300] [DEBUG] [logging.py:11]  Received message [AQID:4731] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T19:02:16.464162+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4732] in chat [ID:448470724]
[2023-04-07T19:02:19.289662+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4734] in chat [ID:448470724]
[2023-04-07T19:02:36.528387+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4737] in chat [ID:448470724]
[2023-04-07T19:02:36.862241+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919025, "callback_query": {"id": "1926167092908592075", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4737, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680894161, "text": "The file has been successfully uploaded.\nIf you don't want to upload any more files, click Finish.", "reply_markup": {"inline_keyboard": [[{"text": "Finish adding", "callback_data": "no-adding"}]]}}, "chat_instance": "1646365164926244667", "data": "no-adding"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 109, in _process_attachments
    await _view_task(await _save_task(callback_query.message, state, user, 'add'), 'add', '', callback_query.message, bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 36, in _view_task
    await _view_files(task=task, response=response)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 73, in _view_files
    response += f"<a href='https://api.telegram.org/file/bot{config.token}/{file['id']}'>üìÑ Document</a>\n"
AttributeError: module 'data.config' has no attribute 'token'

NoneType: None
[2023-04-07T19:05:57.320170+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T19:06:39.793635+0300] [DEBUG] [logging.py:11]  Received message [AQID:4741] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T19:06:45.043159+0300] [DEBUG] [logging.py:11]  Received message [AQID:4743] from user [ID:448470724] in chat [ID:448470724] text "test 4"
[2023-04-07T19:06:47.702067+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:14"] from user [ID:448470724] for message [ID:4744] in chat [ID:448470724]
[2023-04-07T19:06:51.141962+0300] [DEBUG] [logging.py:11]  Received message [AQID:4747] from user [ID:448470724] in chat [ID:448470724] text "14:00"
[2023-04-07T19:06:54.592749+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4748] in chat [ID:448470724]
[2023-04-07T19:06:58.777359+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4750] in chat [ID:448470724]
[2023-04-07T19:07:10.517089+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4753] in chat [ID:448470724]
[2023-04-07T19:07:31.559944+0300] [DEBUG] [logging.py:11]  Received message [AQID:4757] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-07T19:07:33.595363+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_to_do_2"] from user [ID:448470724] for message [ID:4759] in chat [ID:448470724]
[2023-04-07T19:08:14.072221+0300] [DEBUG] [logging.py:11]  Received message [AQID:4761] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-07T19:08:16.503313+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_to_do_13"] from user [ID:448470724] for message [ID:4763] in chat [ID:448470724]
[2023-04-07T19:14:56.391286+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T19:15:21.279608+0300] [DEBUG] [logging.py:11]  Received message [AQID:4766] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T19:15:28.206753+0300] [DEBUG] [logging.py:11]  Received message [AQID:4768] from user [ID:448470724] in chat [ID:448470724] text "test 5"
[2023-04-07T19:15:31.542725+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:8"] from user [ID:448470724] for message [ID:4769] in chat [ID:448470724]
[2023-04-07T19:15:35.109062+0300] [DEBUG] [logging.py:11]  Received message [AQID:4772] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T19:15:37.355181+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4773] in chat [ID:448470724]
[2023-04-07T19:15:40.981192+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4775] in chat [ID:448470724]
[2023-04-07T19:15:58.529751+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4778] in chat [ID:448470724]
[2023-04-07T19:23:34.611152+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T19:23:44.443562+0300] [DEBUG] [logging.py:11]  Received message [AQID:4783] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T19:23:50.898137+0300] [DEBUG] [logging.py:11]  Received message [AQID:4785] from user [ID:448470724] in chat [ID:448470724] text "Task test super"
[2023-04-07T19:23:53.425475+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:7"] from user [ID:448470724] for message [ID:4786] in chat [ID:448470724]
[2023-04-07T19:24:02.256463+0300] [DEBUG] [logging.py:11]  Received message [AQID:4789] from user [ID:448470724] in chat [ID:448470724] text "20:00"
[2023-04-07T19:24:04.688109+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4790] in chat [ID:448470724]
[2023-04-07T19:24:06.194828+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4792] in chat [ID:448470724]
[2023-04-07T19:24:24.087180+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4795] in chat [ID:448470724]
[2023-04-07T19:26:10.671621+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T19:26:14.807194+0300] [DEBUG] [logging.py:11]  Received message [AQID:4800] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T19:26:26.081546+0300] [DEBUG] [logging.py:11]  Received message [AQID:4802] from user [ID:448470724] in chat [ID:448470724] text "task test superpuper"
[2023-04-07T19:26:28.707345+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:26"] from user [ID:448470724] for message [ID:4803] in chat [ID:448470724]
[2023-04-07T19:26:34.287477+0300] [DEBUG] [logging.py:11]  Received message [AQID:4806] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T19:26:41.415537+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4807] in chat [ID:448470724]
[2023-04-07T19:26:43.080145+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4809] in chat [ID:448470724]
[2023-04-07T19:27:08.405224+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4812] in chat [ID:448470724]
[2023-04-07T19:31:34.108942+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T19:31:42.690016+0300] [DEBUG] [logging.py:11]  Received message [AQID:4817] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T19:31:50.397278+0300] [DEBUG] [logging.py:11]  Received message [AQID:4819] from user [ID:448470724] in chat [ID:448470724] text "test super"
[2023-04-07T19:32:07.745769+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:13"] from user [ID:448470724] for message [ID:4820] in chat [ID:448470724]
[2023-04-07T19:32:16.278026+0300] [DEBUG] [logging.py:11]  Received message [AQID:4823] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T19:32:22.917919+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4824] in chat [ID:448470724]
[2023-04-07T19:32:24.901503+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4826] in chat [ID:448470724]
[2023-04-07T19:32:39.987330+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4829] in chat [ID:448470724]
[2023-04-07T19:32:40.267898+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919069, "callback_query": {"id": "1926167096140508847", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4829, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680895964, "text": "The file has been successfully uploaded.\nIf you don't want to upload any more files, click Finish.", "reply_markup": {"inline_keyboard": [[{"text": "Finish adding", "callback_data": "no-adding"}]]}}, "chat_instance": "1646365164926244667", "data": "no-adding"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 109, in _process_attachments
    await _view_task(await _save_task(callback_query.message, state, user, 'add'), 'add', '', callback_query.message, bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 38, in _view_task
    response = await _view_files(task=task, response=response)
TypeError: _view_files() missing 1 required positional argument: 'bot'

NoneType: None
[2023-04-07T19:33:38.267807+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T19:33:38.973668+0300] [DEBUG] [logging.py:11]  Received message [AQID:4832] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T19:33:50.103832+0300] [DEBUG] [logging.py:11]  Received message [AQID:4836] from user [ID:448470724] in chat [ID:448470724] text "task test for best"
[2023-04-07T19:33:52.060913+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:13"] from user [ID:448470724] for message [ID:4837] in chat [ID:448470724]
[2023-04-07T19:33:55.422744+0300] [DEBUG] [logging.py:11]  Received message [AQID:4840] from user [ID:448470724] in chat [ID:448470724] text "17:00"
[2023-04-07T19:33:58.613848+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4841] in chat [ID:448470724]
[2023-04-07T19:34:06.703254+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4843] in chat [ID:448470724]
[2023-04-07T19:34:20.493534+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4846] in chat [ID:448470724]
[2023-04-07T19:34:20.822473+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919078, "callback_query": {"id": "1926167093263159243", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4846, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680896065, "text": "The file has been successfully uploaded.\nIf you don't want to upload any more files, click Finish.", "reply_markup": {"inline_keyboard": [[{"text": "Finish adding", "callback_data": "no-adding"}]]}}, "chat_instance": "1646365164926244667", "data": "no-adding"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 109, in _process_attachments
    await _view_task(await _save_task(callback_query.message, state, user, 'add'), 'add', '', callback_query.message, bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 38, in _view_task
    response = await _view_files(task=task, response=response, bot=Bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 71, in _view_files
    await bot.send_document(chat_id=task.author, document=file['id'])
TypeError: Bot.send_document() missing 1 required positional argument: 'self'

NoneType: None
[2023-04-07T19:35:32.868845+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T19:35:35.376627+0300] [DEBUG] [logging.py:11]  Received message [AQID:4850] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T19:35:40.145191+0300] [DEBUG] [logging.py:11]  Received message [AQID:4852] from user [ID:448470724] in chat [ID:448470724] text "test file"
[2023-04-07T19:35:41.839760+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:19"] from user [ID:448470724] for message [ID:4853] in chat [ID:448470724]
[2023-04-07T19:35:45.329362+0300] [DEBUG] [logging.py:11]  Received message [AQID:4856] from user [ID:448470724] in chat [ID:448470724] text "17:00"
[2023-04-07T19:35:47.518747+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4857] in chat [ID:448470724]
[2023-04-07T19:35:49.304937+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4859] in chat [ID:448470724]
[2023-04-07T19:36:06.836052+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4862] in chat [ID:448470724]
[2023-04-07T19:36:07.149078+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919086, "callback_query": {"id": "1926167093847940847", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4862, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680896172, "text": "The file has been successfully uploaded.\nIf you don't want to upload any more files, click Finish.", "reply_markup": {"inline_keyboard": [[{"text": "Finish adding", "callback_data": "no-adding"}]]}}, "chat_instance": "1646365164926244667", "data": "no-adding"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 109, in _process_attachments
    await _view_task(await _save_task(callback_query.message, state, user, 'add'), 'add', '', callback_query.message, bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 38, in _view_task
    response = await _view_files(task=task, response=response, bot=Bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 71, in _view_files
    await bot.send_document(chat_id=task.author, document=file['id'])
TypeError: Bot.send_document() missing 1 required positional argument: 'self'

NoneType: None
[2023-04-07T19:38:37.619235+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T19:38:43.758843+0300] [DEBUG] [logging.py:11]  Received message [AQID:4866] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T19:38:51.549580+0300] [DEBUG] [logging.py:11]  Received message [AQID:4868] from user [ID:448470724] in chat [ID:448470724] text "test super test"
[2023-04-07T19:38:53.837149+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:21"] from user [ID:448470724] for message [ID:4869] in chat [ID:448470724]
[2023-04-07T19:38:57.259107+0300] [DEBUG] [logging.py:11]  Received message [AQID:4872] from user [ID:448470724] in chat [ID:448470724] text "17:00"
[2023-04-07T19:38:58.995528+0300] [DEBUG] [logging.py:19]  Received callback query [data:"yes"] from user [ID:448470724] for message [ID:4873] in chat [ID:448470724]
[2023-04-07T19:39:02.579281+0300] [DEBUG] [logging.py:11]  Received message [AQID:4875] from user [ID:448470724] in chat [ID:448470724] text "1d"
[2023-04-07T19:39:05.428032+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4876] in chat [ID:448470724]
[2023-04-07T19:39:26.170649+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4879] in chat [ID:448470724]
[2023-04-07T19:42:50.965355+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T19:42:57.338348+0300] [DEBUG] [logging.py:11]  Received message [AQID:4885] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T19:43:05.465961+0300] [DEBUG] [logging.py:11]  Received message [AQID:4887] from user [ID:448470724] in chat [ID:448470724] text "task correct view"
[2023-04-07T19:43:07.907099+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:26"] from user [ID:448470724] for message [ID:4888] in chat [ID:448470724]
[2023-04-07T19:43:12.041709+0300] [DEBUG] [logging.py:11]  Received message [AQID:4891] from user [ID:448470724] in chat [ID:448470724] text "12:00"
[2023-04-07T19:43:14.800423+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4892] in chat [ID:448470724]
[2023-04-07T19:43:17.032939+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4894] in chat [ID:448470724]
[2023-04-07T19:43:30.701171+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4897] in chat [ID:448470724]
[2023-04-07T19:49:16.919260+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T19:49:24.623682+0300] [DEBUG] [logging.py:11]  Received message [AQID:4903] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T19:49:34.087490+0300] [DEBUG] [logging.py:11]  Received message [AQID:4905] from user [ID:448470724] in chat [ID:448470724] text "Task todo"
[2023-04-07T19:49:36.473007+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:20"] from user [ID:448470724] for message [ID:4906] in chat [ID:448470724]
[2023-04-07T19:49:40.123208+0300] [DEBUG] [logging.py:11]  Received message [AQID:4909] from user [ID:448470724] in chat [ID:448470724] text "17:00"
[2023-04-07T19:49:44.834829+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4910] in chat [ID:448470724]
[2023-04-07T19:49:47.297238+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4912] in chat [ID:448470724]
[2023-04-07T19:50:41.750310+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4915] in chat [ID:448470724]
[2023-04-07T19:50:42.173135+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919111, "callback_query": {"id": "1926167093988838267", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4915, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680897044, "text": "The file has been successfully uploaded.\nIf you don't want to upload any more files, click Finish.", "reply_markup": {"inline_keyboard": [[{"text": "Finish adding", "callback_data": "no-adding"}]]}}, "chat_instance": "1646365164926244667", "data": "no-adding"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 109, in _process_attachments
    await _view_task(await _save_task(callback_query.message, state, user, 'add'), 'add', '', callback_query.message, bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 56, in _view_task
    await _view_files(task=task, response=response, bot=bot)
TypeError: _view_files() got an unexpected keyword argument 'response'

NoneType: None
[2023-04-07T19:51:28.320240+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T19:51:32.042707+0300] [DEBUG] [logging.py:11]  Received message [AQID:4920] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T19:51:40.783001+0300] [DEBUG] [logging.py:11]  Received message [AQID:4922] from user [ID:448470724] in chat [ID:448470724] text "Task todo super"
[2023-04-07T19:51:42.266121+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:26"] from user [ID:448470724] for message [ID:4923] in chat [ID:448470724]
[2023-04-07T19:51:45.567532+0300] [DEBUG] [logging.py:11]  Received message [AQID:4926] from user [ID:448470724] in chat [ID:448470724] text "17:00"
[2023-04-07T19:51:47.699540+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4927] in chat [ID:448470724]
[2023-04-07T19:52:28.369107+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4929] in chat [ID:448470724]
[2023-04-07T19:52:53.198973+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4932] in chat [ID:448470724]
[2023-04-07T19:54:26.224644+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T19:54:36.192934+0300] [DEBUG] [logging.py:11]  Received message [AQID:4938] from user [ID:448470724] in chat [ID:448470724] text "New task üÜï"
[2023-04-07T19:54:41.848797+0300] [DEBUG] [logging.py:11]  Received message [AQID:4940] from user [ID:448470724] in chat [ID:448470724] text "todo super"
[2023-04-07T19:54:43.653601+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:27"] from user [ID:448470724] for message [ID:4941] in chat [ID:448470724]
[2023-04-07T19:54:47.468463+0300] [DEBUG] [logging.py:11]  Received message [AQID:4944] from user [ID:448470724] in chat [ID:448470724] text "17:00"
[2023-04-07T19:54:54.822652+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:448470724] for message [ID:4945] in chat [ID:448470724]
[2023-04-07T19:55:22.314625+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:448470724] for message [ID:4947] in chat [ID:448470724]
[2023-04-07T19:55:55.420197+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:448470724] for message [ID:4952] in chat [ID:448470724]
[2023-04-07T19:56:04.466817+0300] [DEBUG] [logging.py:11]  Received message [AQID:4958] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-07T19:56:07.245328+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_to_do_24"] from user [ID:448470724] for message [ID:4960] in chat [ID:448470724]
[2023-04-07T19:56:07.652965+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919130, "callback_query": {"id": "1926167096320489539", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4960, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680897371, "text": "Choose id of task", "reply_markup": {"inline_keyboard": [[{"text": "1", "callback_data": "task_to_do_1"}, {"text": "2", "callback_data": "task_to_do_2"}, {"text": "3", "callback_data": "task_to_do_3"}, {"text": "4", "callback_data": "task_to_do_4"}, {"text": "5", "callback_data": "task_to_do_5"}], [{"text": "6", "callback_data": "task_to_do_6"}, {"text": "7", "callback_data": "task_to_do_7"}, {"text": "8", "callback_data": "task_to_do_8"}, {"text": "9", "callback_data": "task_to_do_9"}, {"text": "10", "callback_data": "task_to_do_10"}], [{"text": "11", "callback_data": "task_to_do_11"}, {"text": "12", "callback_data": "task_to_do_12"}, {"text": "13", "callback_data": "task_to_do_13"}, {"text": "14", "callback_data": "task_to_do_14"}, {"text": "15", "callback_data": "task_to_do_15"}], [{"text": "16", "callback_data": "task_to_do_16"}, {"text": "17", "callback_data": "task_to_do_17"}, {"text": "18", "callback_data": "task_to_do_18"}, {"text": "19", "callback_data": "task_to_do_19"}, {"text": "20", "callback_data": "task_to_do_20"}], [{"text": "21", "callback_data": "task_to_do_21"}, {"text": "22", "callback_data": "task_to_do_22"}, {"text": "23", "callback_data": "task_to_do_23"}, {"text": "24", "callback_data": "task_to_do_24"}]]}}, "chat_instance": "1646365164926244667", "data": "task_to_do_24"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\choose_task.py", line 29, in _choose_task_to_do
    await _view_task(task, 'to-do-choose', response, callback_query.message)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 56, in _view_task
    await _view_files(task=task, bot=bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 71, in _view_files
    await bot.send_document(chat_id=task.author, document=file['id'])
AttributeError: 'NoneType' object has no attribute 'send_document'

NoneType: None
[2023-04-07T20:04:48.490387+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T20:04:52.221704+0300] [DEBUG] [logging.py:11]  Received message [AQID:4965] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-07T20:04:54.656828+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_to_do_24"] from user [ID:448470724] for message [ID:4967] in chat [ID:448470724]
[2023-04-07T20:04:54.857500+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919132, "callback_query": {"id": "1926167094502223048", "from": {"id": 448470724, "is_bot": false, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "language_code": "ru"}, "message": {"message_id": 4967, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 448470724, "first_name": "Ivan", "last_name": "Zolin", "username": "zolin5269", "type": "private"}, "date": 1680897899, "text": "Choose id of task", "reply_markup": {"inline_keyboard": [[{"text": "1", "callback_data": "task_to_do_1"}, {"text": "2", "callback_data": "task_to_do_2"}, {"text": "3", "callback_data": "task_to_do_3"}, {"text": "4", "callback_data": "task_to_do_4"}, {"text": "5", "callback_data": "task_to_do_5"}], [{"text": "6", "callback_data": "task_to_do_6"}, {"text": "7", "callback_data": "task_to_do_7"}, {"text": "8", "callback_data": "task_to_do_8"}, {"text": "9", "callback_data": "task_to_do_9"}, {"text": "10", "callback_data": "task_to_do_10"}], [{"text": "11", "callback_data": "task_to_do_11"}, {"text": "12", "callback_data": "task_to_do_12"}, {"text": "13", "callback_data": "task_to_do_13"}, {"text": "14", "callback_data": "task_to_do_14"}, {"text": "15", "callback_data": "task_to_do_15"}], [{"text": "16", "callback_data": "task_to_do_16"}, {"text": "17", "callback_data": "task_to_do_17"}, {"text": "18", "callback_data": "task_to_do_18"}, {"text": "19", "callback_data": "task_to_do_19"}, {"text": "20", "callback_data": "task_to_do_20"}], [{"text": "21", "callback_data": "task_to_do_21"}, {"text": "22", "callback_data": "task_to_do_22"}, {"text": "23", "callback_data": "task_to_do_23"}, {"text": "24", "callback_data": "task_to_do_24"}]]}}, "chat_instance": "1646365164926244667", "data": "task_to_do_24"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\choose_task.py", line 29, in _choose_task_to_do
    await _view_task(task, 'to-do-choose', response, callback_query.message)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 54, in _view_task
    await _view_files(task=task, bot=bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 69, in _view_files
    await bot.send_document(chat_id=task.author, document=file['id'])
AttributeError: 'NoneType' object has no attribute 'send_document'

NoneType: None
[2023-04-07T20:11:46.969636+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T20:11:49.747169+0300] [DEBUG] [logging.py:11]  Received message [AQID:4970] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-07T20:11:52.343295+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_to_do_24"] from user [ID:448470724] for message [ID:4972] in chat [ID:448470724]
[2023-04-07T20:12:04.608782+0300] [DEBUG] [logging.py:11]  Received message [AQID:4976] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-07T20:12:06.483963+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_to_do_1"] from user [ID:448470724] for message [ID:4978] in chat [ID:448470724]
[2023-04-07T20:12:08.915452+0300] [DEBUG] [logging.py:19]  Received callback query [data:"is_done_task_1"] from user [ID:448470724] for message [ID:4979] in chat [ID:448470724]
[2023-04-07T20:12:18.887306+0300] [DEBUG] [logging.py:11]  Received message [AQID:4982] from user [ID:448470724] in chat [ID:448470724] text "To-do list üìÉ"
[2023-04-07T20:12:27.230205+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_to_do_24"] from user [ID:448470724] for message [ID:4984] in chat [ID:448470724]
[2023-04-07T20:12:29.382269+0300] [DEBUG] [logging.py:19]  Received callback query [data:"is_done_task_24"] from user [ID:448470724] for message [ID:4985] in chat [ID:448470724]
[2023-04-07T20:12:31.915349+0300] [DEBUG] [logging.py:11]  Received message [AQID:4990] from user [ID:448470724] in chat [ID:448470724] text "Completed cases üèÜ"
[2023-04-07T20:12:39.971408+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_completed_24"] from user [ID:448470724] for message [ID:4992] in chat [ID:448470724]
[2023-04-07T20:13:49.624766+0300] [INFO] [main.py:15]  Bot startup
[2023-04-07T20:13:50.146875+0300] [INFO] [users.py:41]  New user 1289011239
[2023-04-07T20:13:50.150240+0300] [DEBUG] [logging.py:11]  Received message [AQID:4996] from user [ID:1289011239] in chat [ID:1289011239] text "/start"
[2023-04-07T20:13:57.611245+0300] [DEBUG] [logging.py:19]  Received callback query [data:"lang_en"] from user [ID:1289011239] for message [ID:4998] in chat [ID:1289011239]
[2023-04-07T20:14:02.932617+0300] [DEBUG] [logging.py:11]  Received message [AQID:5000] from user [ID:1289011239] in chat [ID:1289011239] text "To-do list üìÉ"
[2023-04-07T20:14:08.068706+0300] [DEBUG] [logging.py:11]  Received message [AQID:5002] from user [ID:1289011239] in chat [ID:1289011239] text "New task üÜï"
[2023-04-07T20:14:18.590596+0300] [INFO] [users.py:41]  New user 354866247
[2023-04-07T20:14:18.595485+0300] [DEBUG] [logging.py:11]  Received message [AQID:5004] from user [ID:354866247] in chat [ID:354866247] text "/start"
[2023-04-07T20:14:21.241449+0300] [DEBUG] [logging.py:19]  Received callback query [data:"lang_ru"] from user [ID:354866247] for message [ID:5005] in chat [ID:354866247]
[2023-04-07T20:14:34.665192+0300] [DEBUG] [logging.py:11]  Received message [AQID:5007] from user [ID:354866247] in chat [ID:354866247] text "–ù–∞—Å—Ç—Ä–æ–π–∫–∏ üõ†"
[2023-04-07T20:14:36.508040+0300] [DEBUG] [logging.py:19]  Received callback query [data:"lang_ru"] from user [ID:354866247] for message [ID:5008] in chat [ID:354866247]
[2023-04-07T20:14:38.434000+0300] [DEBUG] [logging.py:11]  Received message [AQID:5010] from user [ID:1289011239] in chat [ID:1289011239] text "Kate wants to buy shaverma"
[2023-04-07T20:14:40.437728+0300] [DEBUG] [logging.py:11]  Received message [AQID:5012] from user [ID:354866247] in chat [ID:354866247] text "/help"
[2023-04-07T20:14:44.848532+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:8"] from user [ID:1289011239] for message [ID:5011] in chat [ID:1289011239]
[2023-04-07T20:14:48.176590+0300] [DEBUG] [logging.py:11]  Received message [AQID:5016] from user [ID:354866247] in chat [ID:354866247] text "–ù–æ–≤–∞—è –∑–∞–¥–∞—á–∞ üÜï"
[2023-04-07T20:14:56.383975+0300] [DEBUG] [logging.py:11]  Received message [AQID:5018] from user [ID:1289011239] in chat [ID:1289011239] text "12:00"
[2023-04-07T20:15:00.764303+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:1289011239] for message [ID:5019] in chat [ID:1289011239]
[2023-04-07T20:15:04.004553+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:1289011239] for message [ID:5021] in chat [ID:1289011239]
[2023-04-07T20:15:08.531085+0300] [DEBUG] [logging.py:11]  Received message [AQID:5025] from user [ID:354866247] in chat [ID:354866247] text "–∑–∞–∑–∞–¥–∞—á–∞—á"
[2023-04-07T20:15:11.015205+0300] [DEBUG] [logging.py:11]  Received message [AQID:5027] from user [ID:1289011239] in chat [ID:1289011239] text "To-do list üìÉ"
[2023-04-07T20:15:16.264824+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:7"] from user [ID:354866247] for message [ID:5026] in chat [ID:354866247]
[2023-04-07T20:15:19.977991+0300] [DEBUG] [logging.py:11]  Received message [AQID:5032] from user [ID:1289011239] in chat [ID:1289011239] text "New task üÜï"
[2023-04-07T20:15:24.513524+0300] [DEBUG] [logging.py:11]  Received message [AQID:5034] from user [ID:354866247] in chat [ID:354866247] text "20:17"
[2023-04-07T20:15:28.537516+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:354866247] for message [ID:5035] in chat [ID:354866247]
[2023-04-07T20:15:31.651116+0300] [DEBUG] [logging.py:19]  Received callback query [data:"start-adding"] from user [ID:354866247] for message [ID:5037] in chat [ID:354866247]
[2023-04-07T20:15:38.276494+0300] [DEBUG] [logging.py:11]  Received message [AQID:5039] from user [ID:1289011239] in chat [ID:1289011239] text "Kate wants to conquer the world"
[2023-04-07T20:15:47.408441+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:354866247] for message [ID:5042] in chat [ID:354866247]
[2023-04-07T20:15:56.209486+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:8"] from user [ID:1289011239] for message [ID:5040] in chat [ID:1289011239]
[2023-04-07T20:16:02.759965+0300] [DEBUG] [logging.py:11]  Received message [AQID:5049] from user [ID:1289011239] in chat [ID:1289011239] text "12:00"
[2023-04-07T20:16:05.176626+0300] [DEBUG] [logging.py:19]  Received callback query [data:"yes"] from user [ID:1289011239] for message [ID:5050] in chat [ID:1289011239]
[2023-04-07T20:16:05.772731+0300] [DEBUG] [logging.py:11]  Received message [AQID:5052] from user [ID:354866247] in chat [ID:354866247] text "/todo"
[2023-04-07T20:16:17.484150+0300] [DEBUG] [logging.py:11]  Received message [AQID:5055] from user [ID:354866247] in chat [ID:354866247] text "/new_task"
[2023-04-07T20:16:36.215682+0300] [DEBUG] [logging.py:11]  Received message [AQID:5057] from user [ID:1289011239] in chat [ID:1289011239] text "1w"
[2023-04-07T20:16:38.699942+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:1289011239] for message [ID:5058] in chat [ID:1289011239]
[2023-04-07T20:16:43.999399+0300] [DEBUG] [logging.py:11]  Received message [AQID:5062] from user [ID:1289011239] in chat [ID:1289011239] text "To-do list üìÉ"
[2023-04-07T20:16:46.742625+0300] [DEBUG] [logging.py:11]  Received message [AQID:5065] from user [ID:354866247] in chat [ID:354866247] text "–∑–∞–∑–∞–∑–∞–¥–∞—á–∞—á2"
[2023-04-07T20:16:48.650715+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:22"] from user [ID:354866247] for message [ID:5066] in chat [ID:354866247]
[2023-04-07T20:16:52.755297+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_to_do_25"] from user [ID:1289011239] for message [ID:5064] in chat [ID:1289011239]
[2023-04-07T20:16:54.274751+0300] [DEBUG] [logging.py:11]  Received message [AQID:5070] from user [ID:354866247] in chat [ID:354866247] text "20:00"
[2023-04-07T20:16:56.298271+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:354866247] for message [ID:5071] in chat [ID:354866247]
[2023-04-07T20:16:56.605170+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_edit_25"] from user [ID:1289011239] for message [ID:5069] in chat [ID:1289011239]
[2023-04-07T20:16:58.116735+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:354866247] for message [ID:5073] in chat [ID:354866247]
[2023-04-07T20:16:59.650389+0300] [DEBUG] [logging.py:19]  Received callback query [data:"edit_text_25"] from user [ID:1289011239] for message [ID:5074] in chat [ID:1289011239]
[2023-04-07T20:17:09.658128+0300] [DEBUG] [logging.py:11]  Received message [AQID:5079] from user [ID:354866247] in chat [ID:354866247] text "/todo"
[2023-04-07T20:17:11.798990+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_to_do_26"] from user [ID:354866247] for message [ID:5081] in chat [ID:354866247]
[2023-04-07T20:17:15.145165+0300] [DEBUG] [logging.py:11]  Received message [AQID:5084] from user [ID:1289011239] in chat [ID:1289011239] text "Kate wants to eat shaverma and drink coffee"
[2023-04-07T20:17:15.497434+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_edit_26"] from user [ID:354866247] for message [ID:5082] in chat [ID:354866247]
[2023-04-07T20:17:19.154702+0300] [DEBUG] [logging.py:19]  Received callback query [data:"main_menu"] from user [ID:1289011239] for message [ID:5086] in chat [ID:1289011239]
[2023-04-07T20:17:23.467577+0300] [DEBUG] [logging.py:11]  Received message [AQID:5090] from user [ID:1289011239] in chat [ID:1289011239] text "Completed cases üèÜ"
[2023-04-07T20:17:28.587990+0300] [DEBUG] [logging.py:11]  Received message [AQID:5092] from user [ID:1289011239] in chat [ID:1289011239] text "/help"
[2023-04-07T20:17:38.911529+0300] [DEBUG] [logging.py:11]  Received message [AQID:5094] from user [ID:1289011239] in chat [ID:1289011239] text "To-do list üìÉ"
[2023-04-07T20:17:42.332048+0300] [DEBUG] [logging.py:11]  Received message [AQID:5097] from user [ID:1289011239] in chat [ID:1289011239] text "Settings üõ†"
[2023-04-07T20:17:48.419239+0300] [DEBUG] [logging.py:11]  Received message [AQID:5101] from user [ID:1289011239] in chat [ID:1289011239] text "Edit task ‚úè"
[2023-04-07T20:18:02.853054+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_edit_25"] from user [ID:1289011239] for message [ID:5103] in chat [ID:1289011239]
[2023-04-07T20:18:04.608135+0300] [DEBUG] [logging.py:19]  Received callback query [data:"edit_time_25"] from user [ID:1289011239] for message [ID:5104] in chat [ID:1289011239]
[2023-04-07T20:18:13.037560+0300] [DEBUG] [logging.py:11]  Received message [AQID:5106] from user [ID:1289011239] in chat [ID:1289011239] text "13:00"
[2023-04-07T20:18:16.420037+0300] [DEBUG] [logging.py:19]  Received callback query [data:"main_menu"] from user [ID:1289011239] for message [ID:5108] in chat [ID:1289011239]
[2023-04-07T20:18:27.944817+0300] [DEBUG] [logging.py:11]  Received message [AQID:5110] from user [ID:1289011239] in chat [ID:1289011239] text "To-do list üìÉ"
[2023-04-07T20:18:30.976397+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_to_do_27"] from user [ID:1289011239] for message [ID:5112] in chat [ID:1289011239]
[2023-04-07T20:18:32.974239+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_edit_27"] from user [ID:1289011239] for message [ID:5113] in chat [ID:1289011239]
[2023-04-07T20:18:59.777897+0300] [DEBUG] [logging.py:19]  Received callback query [data:"edit_text_26"] from user [ID:354866247] for message [ID:5087] in chat [ID:354866247]
[2023-04-07T20:19:06.021091+0300] [DEBUG] [logging.py:11]  Received message [AQID:5120] from user [ID:354866247] in chat [ID:354866247] text "–ø—Ä–∏–≤–µ—Ç"
[2023-04-07T20:19:06.289531+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919206, "message": {"message_id": 5120, "from": {"id": 354866247, "is_bot": false, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "language_code": "ru"}, "chat": {"id": 354866247, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "type": "private"}, "date": 1680898752, "text": "–ø—Ä–∏–≤–µ—Ç"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\edit_task.py", line 33, in _edit_task_text
    await _view_task(get_task_by_id(task_id), 'edit', '', message)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 54, in _view_task
    await _view_files(task=task, bot=bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 69, in _view_files
    await bot.send_document(chat_id=task.author, document=file['id'])
AttributeError: 'NoneType' object has no attribute 'send_document'

NoneType: None
[2023-04-07T20:19:09.820255+0300] [DEBUG] [logging.py:19]  Received callback query [data:"main_menu"] from user [ID:354866247] for message [ID:5122] in chat [ID:354866247]
[2023-04-07T20:19:13.021132+0300] [DEBUG] [logging.py:11]  Received message [AQID:5125] from user [ID:354866247] in chat [ID:354866247] text "–í—ã–ø–æ–ª–Ω–µ–Ω–Ω—ã–µ –¥–µ–ª–∞ üèÜ"
[2023-04-07T20:19:17.412494+0300] [DEBUG] [logging.py:11]  Received message [AQID:5128] from user [ID:354866247] in chat [ID:354866247] text "–†–µ–¥–∞–∫—Ç–∏—Ä–æ–≤–∞—Ç—å –∑–∞–¥–∞—á—É ‚úè"
[2023-04-07T20:19:19.931770+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_edit_28"] from user [ID:354866247] for message [ID:5130] in chat [ID:354866247]
[2023-04-07T20:19:23.678885+0300] [DEBUG] [logging.py:19]  Received callback query [data:"main_menu"] from user [ID:354866247] for message [ID:5131] in chat [ID:354866247]
[2023-04-07T20:19:28.416653+0300] [DEBUG] [logging.py:11]  Received message [AQID:5133] from user [ID:354866247] in chat [ID:354866247] text "–°–ø–∏—Å–æ–∫ —Ç–µ–∫—É—â–∏—Ö –¥–µ–ª üìÉ"
[2023-04-07T20:19:30.833220+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_to_do_28"] from user [ID:354866247] for message [ID:5135] in chat [ID:354866247]
[2023-04-07T20:19:30.974222+0300] [DEBUG] [logging.py:19]  Received callback query [data:"main_menu"] from user [ID:1289011239] for message [ID:5114] in chat [ID:1289011239]
[2023-04-07T20:19:33.945964+0300] [DEBUG] [logging.py:19]  Received callback query [data:"is_done_task_28"] from user [ID:354866247] for message [ID:5136] in chat [ID:354866247]
[2023-04-07T20:19:41.785016+0300] [DEBUG] [logging.py:11]  Received message [AQID:5140] from user [ID:354866247] in chat [ID:354866247] text "–í—ã–ø–æ–ª–Ω–µ–Ω–Ω—ã–µ –¥–µ–ª–∞ üèÜ"
[2023-04-07T20:19:43.353904+0300] [DEBUG] [logging.py:11]  Received message [AQID:5143] from user [ID:354866247] in chat [ID:354866247] text "–†–µ–¥–∞–∫—Ç–∏—Ä–æ–≤–∞—Ç—å –∑–∞–¥–∞—á—É ‚úè"
[2023-04-07T20:19:48.067707+0300] [DEBUG] [logging.py:19]  Received callback query [data:"main_menu"] from user [ID:354866247] for message [ID:5144] in chat [ID:354866247]
[2023-04-07T20:19:49.514683+0300] [DEBUG] [logging.py:11]  Received message [AQID:5147] from user [ID:354866247] in chat [ID:354866247] text "–°–ø–∏—Å–æ–∫ —Ç–µ–∫—É—â–∏—Ö –¥–µ–ª üìÉ"
[2023-04-07T20:19:58.315843+0300] [DEBUG] [logging.py:11]  Received message [AQID:5150] from user [ID:354866247] in chat [ID:354866247] text "–í—ã–ø–æ–ª–Ω–µ–Ω–Ω—ã–µ –¥–µ–ª–∞ üèÜ"
[2023-04-07T20:20:09.668696+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_completed_28"] from user [ID:354866247] for message [ID:5152] in chat [ID:354866247]
[2023-04-07T20:20:15.510796+0300] [DEBUG] [logging.py:11]  Received message [AQID:5154] from user [ID:354866247] in chat [ID:354866247] text "–†–µ–¥–∞–∫—Ç–∏—Ä–æ–≤–∞—Ç—å –∑–∞–¥–∞—á—É ‚úè"
[2023-04-07T20:20:17.641072+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_edit_26"] from user [ID:354866247] for message [ID:5156] in chat [ID:354866247]
[2023-04-07T20:20:19.572971+0300] [DEBUG] [logging.py:19]  Received callback query [data:"edit_date_26"] from user [ID:354866247] for message [ID:5157] in chat [ID:354866247]
[2023-04-07T20:20:27.039458+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:1"] from user [ID:354866247] for message [ID:5159] in chat [ID:354866247]
[2023-04-07T20:20:27.474804+0300] [DEBUG] [error_handler.py:19]  Message is not modified
[2023-04-07T20:20:28.061588+0300] [DEBUG] [logging.py:19]  Received callback query [data:"main_menu"] from user [ID:1289011239] for message [ID:5111] in chat [ID:1289011239]
[2023-04-07T20:20:31.531310+0300] [DEBUG] [logging.py:11]  Received message [AQID:5164] from user [ID:1289011239] in chat [ID:1289011239] text "New task üÜï"
[2023-04-07T20:20:40.270803+0300] [DEBUG] [logging.py:11]  Received message [AQID:5166] from user [ID:1289011239] in chat [ID:1289011239] text "Kate wanna fly"
[2023-04-07T20:20:41.670618+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:IGNORE:2023:4:0"] from user [ID:1289011239] for message [ID:5167] in chat [ID:1289011239]
[2023-04-07T20:20:41.733501+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919232, "callback_query": {"id": "5536261115714649659", "from": {"id": 1289011239, "is_bot": false, "first_name": "Katy", "last_name": "Alien", "username": "Kattttalien", "language_code": "ru"}, "message": {"message_id": 5167, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 1289011239, "first_name": "Katy", "last_name": "Alien", "username": "Kattttalien", "type": "private"}, "date": 1680898847, "text": "When should the task be done?", "reply_markup": {"inline_keyboard": [[{"text": "<<", "callback_data": "simple_calendar:PREV-YEAR:2023:4:1"}, {"text": "April 2023", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": ">>", "callback_data": "simple_calendar:NEXT-YEAR:2023:4:1"}], [{"text": "Mo", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Tu", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "We", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Th", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Fr", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Sa", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Su", "callback_data": "simple_calendar:IGNORE:2023:4:0"}], [{"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "1", "callback_data": "simple_calendar:DAY:2023:4:1"}, {"text": "2", "callback_data": "simple_calendar:DAY:2023:4:2"}], [{"text": "3", "callback_data": "simple_calendar:DAY:2023:4:3"}, {"text": "4", "callback_data": "simple_calendar:DAY:2023:4:4"}, {"text": "5", "callback_data": "simple_calendar:DAY:2023:4:5"}, {"text": "6", "callback_data": "simple_calendar:DAY:2023:4:6"}, {"text": "7", "callback_data": "simple_calendar:DAY:2023:4:7"}, {"text": "8", "callback_data": "simple_calendar:DAY:2023:4:8"}, {"text": "9", "callback_data": "simple_calendar:DAY:2023:4:9"}], [{"text": "10", "callback_data": "simple_calendar:DAY:2023:4:10"}, {"text": "11", "callback_data": "simple_calendar:DAY:2023:4:11"}, {"text": "12", "callback_data": "simple_calendar:DAY:2023:4:12"}, {"text": "13", "callback_data": "simple_calendar:DAY:2023:4:13"}, {"text": "14", "callback_data": "simple_calendar:DAY:2023:4:14"}, {"text": "15", "callback_data": "simple_calendar:DAY:2023:4:15"}, {"text": "16", "callback_data": "simple_calendar:DAY:2023:4:16"}], [{"text": "17", "callback_data": "simple_calendar:DAY:2023:4:17"}, {"text": "18", "callback_data": "simple_calendar:DAY:2023:4:18"}, {"text": "19", "callback_data": "simple_calendar:DAY:2023:4:19"}, {"text": "20", "callback_data": "simple_calendar:DAY:2023:4:20"}, {"text": "21", "callback_data": "simple_calendar:DAY:2023:4:21"}, {"text": "22", "callback_data": "simple_calendar:DAY:2023:4:22"}, {"text": "23", "callback_data": "simple_calendar:DAY:2023:4:23"}], [{"text": "24", "callback_data": "simple_calendar:DAY:2023:4:24"}, {"text": "25", "callback_data": "simple_calendar:DAY:2023:4:25"}, {"text": "26", "callback_data": "simple_calendar:DAY:2023:4:26"}, {"text": "27", "callback_data": "simple_calendar:DAY:2023:4:27"}, {"text": "28", "callback_data": "simple_calendar:DAY:2023:4:28"}, {"text": "29", "callback_data": "simple_calendar:DAY:2023:4:29"}, {"text": "30", "callback_data": "simple_calendar:DAY:2023:4:30"}], [{"text": "<", "callback_data": "simple_calendar:PREV-MONTH:2023:4:30"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": ">", "callback_data": "simple_calendar:NEXT-MONTH:2023:4:30"}]]}}, "chat_instance": "8457727828278776801", "data": "simple_calendar:IGNORE:2023:4:0"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\create_task.py", line 27, in _process_date
    selected, date = await _body_set_date(callback_query, callback_data, state)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\task_helpers.py", line 67, in _body_set_date
    data['date'] = date.strftime("%d.%m.%Y")
AttributeError: 'NoneType' object has no attribute 'strftime'

NoneType: None
[2023-04-07T20:20:42.009772+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:IGNORE:2023:4:0"] from user [ID:354866247] for message [ID:5162] in chat [ID:354866247]
[2023-04-07T20:20:42.070424+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919233, "callback_query": {"id": "1524138927297316449", "from": {"id": 354866247, "is_bot": false, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "language_code": "ru"}, "message": {"message_id": 5162, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 354866247, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "type": "private"}, "date": 1680898834, "text": "Wrong date. Please enter the day before today", "reply_markup": {"inline_keyboard": [[{"text": "<<", "callback_data": "simple_calendar:PREV-YEAR:2023:4:1"}, {"text": "April 2023", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": ">>", "callback_data": "simple_calendar:NEXT-YEAR:2023:4:1"}], [{"text": "Mo", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Tu", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "We", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Th", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Fr", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Sa", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Su", "callback_data": "simple_calendar:IGNORE:2023:4:0"}], [{"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "1", "callback_data": "simple_calendar:DAY:2023:4:1"}, {"text": "2", "callback_data": "simple_calendar:DAY:2023:4:2"}], [{"text": "3", "callback_data": "simple_calendar:DAY:2023:4:3"}, {"text": "4", "callback_data": "simple_calendar:DAY:2023:4:4"}, {"text": "5", "callback_data": "simple_calendar:DAY:2023:4:5"}, {"text": "6", "callback_data": "simple_calendar:DAY:2023:4:6"}, {"text": "7", "callback_data": "simple_calendar:DAY:2023:4:7"}, {"text": "8", "callback_data": "simple_calendar:DAY:2023:4:8"}, {"text": "9", "callback_data": "simple_calendar:DAY:2023:4:9"}], [{"text": "10", "callback_data": "simple_calendar:DAY:2023:4:10"}, {"text": "11", "callback_data": "simple_calendar:DAY:2023:4:11"}, {"text": "12", "callback_data": "simple_calendar:DAY:2023:4:12"}, {"text": "13", "callback_data": "simple_calendar:DAY:2023:4:13"}, {"text": "14", "callback_data": "simple_calendar:DAY:2023:4:14"}, {"text": "15", "callback_data": "simple_calendar:DAY:2023:4:15"}, {"text": "16", "callback_data": "simple_calendar:DAY:2023:4:16"}], [{"text": "17", "callback_data": "simple_calendar:DAY:2023:4:17"}, {"text": "18", "callback_data": "simple_calendar:DAY:2023:4:18"}, {"text": "19", "callback_data": "simple_calendar:DAY:2023:4:19"}, {"text": "20", "callback_data": "simple_calendar:DAY:2023:4:20"}, {"text": "21", "callback_data": "simple_calendar:DAY:2023:4:21"}, {"text": "22", "callback_data": "simple_calendar:DAY:2023:4:22"}, {"text": "23", "callback_data": "simple_calendar:DAY:2023:4:23"}], [{"text": "24", "callback_data": "simple_calendar:DAY:2023:4:24"}, {"text": "25", "callback_data": "simple_calendar:DAY:2023:4:25"}, {"text": "26", "callback_data": "simple_calendar:DAY:2023:4:26"}, {"text": "27", "callback_data": "simple_calendar:DAY:2023:4:27"}, {"text": "28", "callback_data": "simple_calendar:DAY:2023:4:28"}, {"text": "29", "callback_data": "simple_calendar:DAY:2023:4:29"}, {"text": "30", "callback_data": "simple_calendar:DAY:2023:4:30"}], [{"text": "<", "callback_data": "simple_calendar:PREV-MONTH:2023:4:30"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": ">", "callback_data": "simple_calendar:NEXT-MONTH:2023:4:30"}]]}}, "chat_instance": "8164716676354837736", "data": "simple_calendar:IGNORE:2023:4:0"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\edit_task.py", line 49, in _edit_task_date
    selected, task_date = await _body_set_date(callback_query, callback_data, state)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\task_helpers.py", line 67, in _body_set_date
    data['date'] = date.strftime("%d.%m.%Y")
AttributeError: 'NoneType' object has no attribute 'strftime'

NoneType: None
[2023-04-07T20:20:43.439871+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:1"] from user [ID:354866247] for message [ID:5162] in chat [ID:354866247]
[2023-04-07T20:20:43.850711+0300] [DEBUG] [error_handler.py:19]  Message is not modified
[2023-04-07T20:20:44.089861+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:1"] from user [ID:1289011239] for message [ID:5167] in chat [ID:1289011239]
[2023-04-07T20:20:44.595490+0300] [DEBUG] [error_handler.py:19]  Message is not modified
[2023-04-07T20:20:51.941764+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:7"] from user [ID:1289011239] for message [ID:5171] in chat [ID:1289011239]
[2023-04-07T20:20:52.206726+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:IGNORE:2023:4:0"] from user [ID:354866247] for message [ID:5169] in chat [ID:354866247]
[2023-04-07T20:20:52.288704+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919237, "callback_query": {"id": "1524138926542444292", "from": {"id": 354866247, "is_bot": false, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "language_code": "ru"}, "message": {"message_id": 5169, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 354866247, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "type": "private"}, "date": 1680898850, "text": "Wrong date. Please enter the day before today", "reply_markup": {"inline_keyboard": [[{"text": "<<", "callback_data": "simple_calendar:PREV-YEAR:2023:4:1"}, {"text": "April 2023", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": ">>", "callback_data": "simple_calendar:NEXT-YEAR:2023:4:1"}], [{"text": "Mo", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Tu", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "We", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Th", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Fr", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Sa", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Su", "callback_data": "simple_calendar:IGNORE:2023:4:0"}], [{"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "1", "callback_data": "simple_calendar:DAY:2023:4:1"}, {"text": "2", "callback_data": "simple_calendar:DAY:2023:4:2"}], [{"text": "3", "callback_data": "simple_calendar:DAY:2023:4:3"}, {"text": "4", "callback_data": "simple_calendar:DAY:2023:4:4"}, {"text": "5", "callback_data": "simple_calendar:DAY:2023:4:5"}, {"text": "6", "callback_data": "simple_calendar:DAY:2023:4:6"}, {"text": "7", "callback_data": "simple_calendar:DAY:2023:4:7"}, {"text": "8", "callback_data": "simple_calendar:DAY:2023:4:8"}, {"text": "9", "callback_data": "simple_calendar:DAY:2023:4:9"}], [{"text": "10", "callback_data": "simple_calendar:DAY:2023:4:10"}, {"text": "11", "callback_data": "simple_calendar:DAY:2023:4:11"}, {"text": "12", "callback_data": "simple_calendar:DAY:2023:4:12"}, {"text": "13", "callback_data": "simple_calendar:DAY:2023:4:13"}, {"text": "14", "callback_data": "simple_calendar:DAY:2023:4:14"}, {"text": "15", "callback_data": "simple_calendar:DAY:2023:4:15"}, {"text": "16", "callback_data": "simple_calendar:DAY:2023:4:16"}], [{"text": "17", "callback_data": "simple_calendar:DAY:2023:4:17"}, {"text": "18", "callback_data": "simple_calendar:DAY:2023:4:18"}, {"text": "19", "callback_data": "simple_calendar:DAY:2023:4:19"}, {"text": "20", "callback_data": "simple_calendar:DAY:2023:4:20"}, {"text": "21", "callback_data": "simple_calendar:DAY:2023:4:21"}, {"text": "22", "callback_data": "simple_calendar:DAY:2023:4:22"}, {"text": "23", "callback_data": "simple_calendar:DAY:2023:4:23"}], [{"text": "24", "callback_data": "simple_calendar:DAY:2023:4:24"}, {"text": "25", "callback_data": "simple_calendar:DAY:2023:4:25"}, {"text": "26", "callback_data": "simple_calendar:DAY:2023:4:26"}, {"text": "27", "callback_data": "simple_calendar:DAY:2023:4:27"}, {"text": "28", "callback_data": "simple_calendar:DAY:2023:4:28"}, {"text": "29", "callback_data": "simple_calendar:DAY:2023:4:29"}, {"text": "30", "callback_data": "simple_calendar:DAY:2023:4:30"}], [{"text": "<", "callback_data": "simple_calendar:PREV-MONTH:2023:4:30"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": ">", "callback_data": "simple_calendar:NEXT-MONTH:2023:4:30"}]]}}, "chat_instance": "8164716676354837736", "data": "simple_calendar:IGNORE:2023:4:0"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\edit_task.py", line 49, in _edit_task_date
    selected, task_date = await _body_set_date(callback_query, callback_data, state)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\task_helpers.py", line 67, in _body_set_date
    data['date'] = date.strftime("%d.%m.%Y")
AttributeError: 'NoneType' object has no attribute 'strftime'

NoneType: None
[2023-04-07T20:20:52.511267+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:NEXT-MONTH:2023:4:30"] from user [ID:354866247] for message [ID:5169] in chat [ID:354866247]
[2023-04-07T20:20:52.651679+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919238, "callback_query": {"id": "1524138927829527102", "from": {"id": 354866247, "is_bot": false, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "language_code": "ru"}, "message": {"message_id": 5169, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 354866247, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "type": "private"}, "date": 1680898850, "text": "Wrong date. Please enter the day before today", "reply_markup": {"inline_keyboard": [[{"text": "<<", "callback_data": "simple_calendar:PREV-YEAR:2023:4:1"}, {"text": "April 2023", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": ">>", "callback_data": "simple_calendar:NEXT-YEAR:2023:4:1"}], [{"text": "Mo", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Tu", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "We", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Th", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Fr", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Sa", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "Su", "callback_data": "simple_calendar:IGNORE:2023:4:0"}], [{"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": "1", "callback_data": "simple_calendar:DAY:2023:4:1"}, {"text": "2", "callback_data": "simple_calendar:DAY:2023:4:2"}], [{"text": "3", "callback_data": "simple_calendar:DAY:2023:4:3"}, {"text": "4", "callback_data": "simple_calendar:DAY:2023:4:4"}, {"text": "5", "callback_data": "simple_calendar:DAY:2023:4:5"}, {"text": "6", "callback_data": "simple_calendar:DAY:2023:4:6"}, {"text": "7", "callback_data": "simple_calendar:DAY:2023:4:7"}, {"text": "8", "callback_data": "simple_calendar:DAY:2023:4:8"}, {"text": "9", "callback_data": "simple_calendar:DAY:2023:4:9"}], [{"text": "10", "callback_data": "simple_calendar:DAY:2023:4:10"}, {"text": "11", "callback_data": "simple_calendar:DAY:2023:4:11"}, {"text": "12", "callback_data": "simple_calendar:DAY:2023:4:12"}, {"text": "13", "callback_data": "simple_calendar:DAY:2023:4:13"}, {"text": "14", "callback_data": "simple_calendar:DAY:2023:4:14"}, {"text": "15", "callback_data": "simple_calendar:DAY:2023:4:15"}, {"text": "16", "callback_data": "simple_calendar:DAY:2023:4:16"}], [{"text": "17", "callback_data": "simple_calendar:DAY:2023:4:17"}, {"text": "18", "callback_data": "simple_calendar:DAY:2023:4:18"}, {"text": "19", "callback_data": "simple_calendar:DAY:2023:4:19"}, {"text": "20", "callback_data": "simple_calendar:DAY:2023:4:20"}, {"text": "21", "callback_data": "simple_calendar:DAY:2023:4:21"}, {"text": "22", "callback_data": "simple_calendar:DAY:2023:4:22"}, {"text": "23", "callback_data": "simple_calendar:DAY:2023:4:23"}], [{"text": "24", "callback_data": "simple_calendar:DAY:2023:4:24"}, {"text": "25", "callback_data": "simple_calendar:DAY:2023:4:25"}, {"text": "26", "callback_data": "simple_calendar:DAY:2023:4:26"}, {"text": "27", "callback_data": "simple_calendar:DAY:2023:4:27"}, {"text": "28", "callback_data": "simple_calendar:DAY:2023:4:28"}, {"text": "29", "callback_data": "simple_calendar:DAY:2023:4:29"}, {"text": "30", "callback_data": "simple_calendar:DAY:2023:4:30"}], [{"text": "<", "callback_data": "simple_calendar:PREV-MONTH:2023:4:30"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:4:0"}, {"text": ">", "callback_data": "simple_calendar:NEXT-MONTH:2023:4:30"}]]}}, "chat_instance": "8164716676354837736", "data": "simple_calendar:NEXT-MONTH:2023:4:30"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\edit_task.py", line 49, in _edit_task_date
    selected, task_date = await _body_set_date(callback_query, callback_data, state)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\task_helpers.py", line 67, in _body_set_date
    data['date'] = date.strftime("%d.%m.%Y")
AttributeError: 'NoneType' object has no attribute 'strftime'

NoneType: None
[2023-04-07T20:20:53.338407+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:NEXT-MONTH:2023:5:0"] from user [ID:354866247] for message [ID:5169] in chat [ID:354866247]
[2023-04-07T20:20:53.492742+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919239, "callback_query": {"id": "1524138928180998745", "from": {"id": 354866247, "is_bot": false, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "language_code": "ru"}, "message": {"message_id": 5169, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 354866247, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "type": "private"}, "date": 1680898850, "edit_date": 1680898859, "text": "Wrong date. Please enter the day before today", "reply_markup": {"inline_keyboard": [[{"text": "<<", "callback_data": "simple_calendar:PREV-YEAR:2023:5:1"}, {"text": "May 2023", "callback_data": "simple_calendar:IGNORE:2023:5:0"}, {"text": ">>", "callback_data": "simple_calendar:NEXT-YEAR:2023:5:1"}], [{"text": "Mo", "callback_data": "simple_calendar:IGNORE:2023:5:0"}, {"text": "Tu", "callback_data": "simple_calendar:IGNORE:2023:5:0"}, {"text": "We", "callback_data": "simple_calendar:IGNORE:2023:5:0"}, {"text": "Th", "callback_data": "simple_calendar:IGNORE:2023:5:0"}, {"text": "Fr", "callback_data": "simple_calendar:IGNORE:2023:5:0"}, {"text": "Sa", "callback_data": "simple_calendar:IGNORE:2023:5:0"}, {"text": "Su", "callback_data": "simple_calendar:IGNORE:2023:5:0"}], [{"text": "1", "callback_data": "simple_calendar:DAY:2023:5:1"}, {"text": "2", "callback_data": "simple_calendar:DAY:2023:5:2"}, {"text": "3", "callback_data": "simple_calendar:DAY:2023:5:3"}, {"text": "4", "callback_data": "simple_calendar:DAY:2023:5:4"}, {"text": "5", "callback_data": "simple_calendar:DAY:2023:5:5"}, {"text": "6", "callback_data": "simple_calendar:DAY:2023:5:6"}, {"text": "7", "callback_data": "simple_calendar:DAY:2023:5:7"}], [{"text": "8", "callback_data": "simple_calendar:DAY:2023:5:8"}, {"text": "9", "callback_data": "simple_calendar:DAY:2023:5:9"}, {"text": "10", "callback_data": "simple_calendar:DAY:2023:5:10"}, {"text": "11", "callback_data": "simple_calendar:DAY:2023:5:11"}, {"text": "12", "callback_data": "simple_calendar:DAY:2023:5:12"}, {"text": "13", "callback_data": "simple_calendar:DAY:2023:5:13"}, {"text": "14", "callback_data": "simple_calendar:DAY:2023:5:14"}], [{"text": "15", "callback_data": "simple_calendar:DAY:2023:5:15"}, {"text": "16", "callback_data": "simple_calendar:DAY:2023:5:16"}, {"text": "17", "callback_data": "simple_calendar:DAY:2023:5:17"}, {"text": "18", "callback_data": "simple_calendar:DAY:2023:5:18"}, {"text": "19", "callback_data": "simple_calendar:DAY:2023:5:19"}, {"text": "20", "callback_data": "simple_calendar:DAY:2023:5:20"}, {"text": "21", "callback_data": "simple_calendar:DAY:2023:5:21"}], [{"text": "22", "callback_data": "simple_calendar:DAY:2023:5:22"}, {"text": "23", "callback_data": "simple_calendar:DAY:2023:5:23"}, {"text": "24", "callback_data": "simple_calendar:DAY:2023:5:24"}, {"text": "25", "callback_data": "simple_calendar:DAY:2023:5:25"}, {"text": "26", "callback_data": "simple_calendar:DAY:2023:5:26"}, {"text": "27", "callback_data": "simple_calendar:DAY:2023:5:27"}, {"text": "28", "callback_data": "simple_calendar:DAY:2023:5:28"}], [{"text": "29", "callback_data": "simple_calendar:DAY:2023:5:29"}, {"text": "30", "callback_data": "simple_calendar:DAY:2023:5:30"}, {"text": "31", "callback_data": "simple_calendar:DAY:2023:5:31"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:5:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:5:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:5:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:5:0"}], [{"text": "<", "callback_data": "simple_calendar:PREV-MONTH:2023:5:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:5:0"}, {"text": ">", "callback_data": "simple_calendar:NEXT-MONTH:2023:5:0"}]]}}, "chat_instance": "8164716676354837736", "data": "simple_calendar:NEXT-MONTH:2023:5:0"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\edit_task.py", line 49, in _edit_task_date
    selected, task_date = await _body_set_date(callback_query, callback_data, state)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\task_helpers.py", line 67, in _body_set_date
    data['date'] = date.strftime("%d.%m.%Y")
AttributeError: 'NoneType' object has no attribute 'strftime'

NoneType: None
[2023-04-07T20:20:56.960264+0300] [DEBUG] [logging.py:11]  Received message [AQID:5174] from user [ID:1289011239] in chat [ID:1289011239] text "111111"
[2023-04-07T20:21:10.778940+0300] [DEBUG] [logging.py:11]  Received message [AQID:5178] from user [ID:1289011239] in chat [ID:1289011239] text "00:12"
[2023-04-07T20:21:22.717815+0300] [DEBUG] [logging.py:11]  Received message [AQID:5180] from user [ID:1289011239] in chat [ID:1289011239] text "To-do list üìÉ"
[2023-04-07T20:21:23.139195+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:6:23"] from user [ID:354866247] for message [ID:5169] in chat [ID:354866247]
[2023-04-07T20:21:23.539566+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919245, "callback_query": {"id": "1524138925811446905", "from": {"id": 354866247, "is_bot": false, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "language_code": "ru"}, "message": {"message_id": 5169, "from": {"id": 6237340947, "is_bot": true, "first_name": "ToDoList Bot", "username": "to_do_list_tg_bot"}, "chat": {"id": 354866247, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "type": "private"}, "date": 1680898850, "edit_date": 1680898860, "text": "Wrong date. Please enter the day before today", "reply_markup": {"inline_keyboard": [[{"text": "<<", "callback_data": "simple_calendar:PREV-YEAR:2023:6:1"}, {"text": "June 2023", "callback_data": "simple_calendar:IGNORE:2023:6:0"}, {"text": ">>", "callback_data": "simple_calendar:NEXT-YEAR:2023:6:1"}], [{"text": "Mo", "callback_data": "simple_calendar:IGNORE:2023:6:0"}, {"text": "Tu", "callback_data": "simple_calendar:IGNORE:2023:6:0"}, {"text": "We", "callback_data": "simple_calendar:IGNORE:2023:6:0"}, {"text": "Th", "callback_data": "simple_calendar:IGNORE:2023:6:0"}, {"text": "Fr", "callback_data": "simple_calendar:IGNORE:2023:6:0"}, {"text": "Sa", "callback_data": "simple_calendar:IGNORE:2023:6:0"}, {"text": "Su", "callback_data": "simple_calendar:IGNORE:2023:6:0"}], [{"text": " ", "callback_data": "simple_calendar:IGNORE:2023:6:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:6:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:6:0"}, {"text": "1", "callback_data": "simple_calendar:DAY:2023:6:1"}, {"text": "2", "callback_data": "simple_calendar:DAY:2023:6:2"}, {"text": "3", "callback_data": "simple_calendar:DAY:2023:6:3"}, {"text": "4", "callback_data": "simple_calendar:DAY:2023:6:4"}], [{"text": "5", "callback_data": "simple_calendar:DAY:2023:6:5"}, {"text": "6", "callback_data": "simple_calendar:DAY:2023:6:6"}, {"text": "7", "callback_data": "simple_calendar:DAY:2023:6:7"}, {"text": "8", "callback_data": "simple_calendar:DAY:2023:6:8"}, {"text": "9", "callback_data": "simple_calendar:DAY:2023:6:9"}, {"text": "10", "callback_data": "simple_calendar:DAY:2023:6:10"}, {"text": "11", "callback_data": "simple_calendar:DAY:2023:6:11"}], [{"text": "12", "callback_data": "simple_calendar:DAY:2023:6:12"}, {"text": "13", "callback_data": "simple_calendar:DAY:2023:6:13"}, {"text": "14", "callback_data": "simple_calendar:DAY:2023:6:14"}, {"text": "15", "callback_data": "simple_calendar:DAY:2023:6:15"}, {"text": "16", "callback_data": "simple_calendar:DAY:2023:6:16"}, {"text": "17", "callback_data": "simple_calendar:DAY:2023:6:17"}, {"text": "18", "callback_data": "simple_calendar:DAY:2023:6:18"}], [{"text": "19", "callback_data": "simple_calendar:DAY:2023:6:19"}, {"text": "20", "callback_data": "simple_calendar:DAY:2023:6:20"}, {"text": "21", "callback_data": "simple_calendar:DAY:2023:6:21"}, {"text": "22", "callback_data": "simple_calendar:DAY:2023:6:22"}, {"text": "23", "callback_data": "simple_calendar:DAY:2023:6:23"}, {"text": "24", "callback_data": "simple_calendar:DAY:2023:6:24"}, {"text": "25", "callback_data": "simple_calendar:DAY:2023:6:25"}], [{"text": "26", "callback_data": "simple_calendar:DAY:2023:6:26"}, {"text": "27", "callback_data": "simple_calendar:DAY:2023:6:27"}, {"text": "28", "callback_data": "simple_calendar:DAY:2023:6:28"}, {"text": "29", "callback_data": "simple_calendar:DAY:2023:6:29"}, {"text": "30", "callback_data": "simple_calendar:DAY:2023:6:30"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:6:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:6:0"}], [{"text": "<", "callback_data": "simple_calendar:PREV-MONTH:2023:6:0"}, {"text": " ", "callback_data": "simple_calendar:IGNORE:2023:6:0"}, {"text": ">", "callback_data": "simple_calendar:NEXT-MONTH:2023:6:0"}]]}}, "chat_instance": "8164716676354837736", "data": "simple_calendar:DAY:2023:6:23"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\edit_task.py", line 53, in _edit_task_date
    await _view_task(get_task_by_id(task_id), 'edit', '', callback_query.message)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 54, in _view_task
    await _view_files(task=task, bot=bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 69, in _view_files
    await bot.send_document(chat_id=task.author, document=file['id'])
AttributeError: 'NoneType' object has no attribute 'send_document'

NoneType: None
[2023-04-07T20:21:30.395035+0300] [DEBUG] [logging.py:11]  Received message [AQID:5185] from user [ID:1289011239] in chat [ID:1289011239] text "12:30"
[2023-04-07T20:21:31.253201+0300] [DEBUG] [logging.py:19]  Received callback query [data:"edit_time_26"] from user [ID:354866247] for message [ID:5184] in chat [ID:354866247]
[2023-04-07T20:21:44.781747+0300] [DEBUG] [logging.py:11]  Received message [AQID:5188] from user [ID:1289011239] in chat [ID:1289011239] text "23:59"
[2023-04-07T20:21:49.969607+0300] [DEBUG] [logging.py:19]  Received callback query [data:"yes"] from user [ID:1289011239] for message [ID:5189] in chat [ID:1289011239]
[2023-04-07T20:21:55.062979+0300] [DEBUG] [logging.py:11]  Received message [AQID:5191] from user [ID:1289011239] in chat [ID:1289011239] text "1mm"
[2023-04-07T20:22:20.896652+0300] [DEBUG] [logging.py:11]  Received message [AQID:5193] from user [ID:354866247] in chat [ID:354866247] text "–ù–æ–≤–∞—è –∑–∞–¥–∞—á–∞ üÜï"
[2023-04-07T20:22:29.039191+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:1289011239] for message [ID:5192] in chat [ID:1289011239]
[2023-04-07T20:22:33.433640+0300] [DEBUG] [logging.py:11]  Received message [AQID:5198] from user [ID:354866247] in chat [ID:354866247] text "20:25"
[2023-04-07T20:22:33.630098+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919253, "message": {"message_id": 5198, "from": {"id": 354866247, "is_bot": false, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "language_code": "ru"}, "chat": {"id": 354866247, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "type": "private"}, "date": 1680898960, "text": "20:25"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\edit_task.py", line 79, in _edit_task_time
    await _view_task(get_task_by_id(task_id), 'edit', '', message)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 54, in _view_task
    await _view_files(task=task, bot=bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 69, in _view_files
    await bot.send_document(chat_id=task.author, document=file['id'])
AttributeError: 'NoneType' object has no attribute 'send_document'

NoneType: None
[2023-04-07T20:22:34.752751+0300] [DEBUG] [logging.py:19]  Received callback query [data:"edit_periodicity_26"] from user [ID:354866247] for message [ID:5200] in chat [ID:354866247]
[2023-04-07T20:22:44.583575+0300] [DEBUG] [logging.py:11]  Received message [AQID:5202] from user [ID:1289011239] in chat [ID:1289011239] text "New task üÜï"
[2023-04-07T20:22:53.041835+0300] [DEBUG] [logging.py:11]  Received message [AQID:5204] from user [ID:1289011239] in chat [ID:1289011239] text "Hurray"
[2023-04-07T20:22:54.954578+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:15"] from user [ID:1289011239] for message [ID:5205] in chat [ID:1289011239]
[2023-04-07T20:22:58.606894+0300] [DEBUG] [logging.py:11]  Received message [AQID:5208] from user [ID:1289011239] in chat [ID:1289011239] text "12:00"
[2023-04-07T20:23:00.708003+0300] [DEBUG] [logging.py:19]  Received callback query [data:"yes"] from user [ID:1289011239] for message [ID:5209] in chat [ID:1289011239]
[2023-04-07T20:23:07.015166+0300] [DEBUG] [logging.py:11]  Received message [AQID:5211] from user [ID:1289011239] in chat [ID:1289011239] text "1234"
[2023-04-07T20:23:18.781124+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:1289011239] for message [ID:5212] in chat [ID:1289011239]
[2023-04-07T20:23:28.046864+0300] [DEBUG] [logging.py:11]  Received message [AQID:5216] from user [ID:354866247] in chat [ID:354866247] text "10 gh"
[2023-04-07T20:23:28.259682+0300] [ERROR] [error_handler.py:56]  Update: {"update_id": 178919262, "message": {"message_id": 5216, "from": {"id": 354866247, "is_bot": false, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "language_code": "ru"}, "chat": {"id": 354866247, "first_name": "–ú–∏—à–∞", "username": "mesha159753", "type": "private"}, "date": 1680899014, "text": "10 gh"}} 
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\errors\error_handler.py", line 52, in errors_handler
    raise exception
  File "c:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 1394, in process_response
    response = task.result()
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\bot\handlers\tasks\edit_task.py", line 112, in _edit_task_text
    await _view_task(get_task_by_id(task_id), 'edit', '', message)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 54, in _view_task
    await _view_files(task=task, bot=bot)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist-Telegram-bot\utils\view_task.py", line 69, in _view_files
    await bot.send_document(chat_id=task.author, document=file['id'])
AttributeError: 'NoneType' object has no attribute 'send_document'

NoneType: None
[2023-04-07T20:23:35.844863+0300] [DEBUG] [logging.py:11]  Received message [AQID:5219] from user [ID:1289011239] in chat [ID:1289011239] text "New task üÜï"
[2023-04-07T20:23:42.268995+0300] [DEBUG] [logging.py:19]  Received callback query [data:"main_menu"] from user [ID:354866247] for message [ID:5218] in chat [ID:354866247]
[2023-04-07T20:23:44.365781+0300] [DEBUG] [logging.py:11]  Received message [AQID:5222] from user [ID:1289011239] in chat [ID:1289011239] text "O mama mia"
[2023-04-07T20:23:46.026959+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:15"] from user [ID:1289011239] for message [ID:5223] in chat [ID:1289011239]
[2023-04-07T20:23:49.532286+0300] [DEBUG] [logging.py:11]  Received message [AQID:5226] from user [ID:1289011239] in chat [ID:1289011239] text "12:00"
[2023-04-07T20:23:51.513169+0300] [DEBUG] [logging.py:19]  Received callback query [data:"yes"] from user [ID:1289011239] for message [ID:5227] in chat [ID:1289011239]
[2023-04-07T20:23:55.867433+0300] [DEBUG] [logging.py:11]  Received message [AQID:5229] from user [ID:1289011239] in chat [ID:1289011239] text "1234m"
[2023-04-07T20:23:56.995806+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:1289011239] for message [ID:5230] in chat [ID:1289011239]
[2023-04-07T20:24:04.442786+0300] [DEBUG] [logging.py:11]  Received message [AQID:5234] from user [ID:1289011239] in chat [ID:1289011239] text "To-do list üìÉ"
[2023-04-07T20:24:07.244856+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_to_do_30"] from user [ID:1289011239] for message [ID:5236] in chat [ID:1289011239]
[2023-04-07T20:24:18.077040+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_edit_30"] from user [ID:1289011239] for message [ID:5237] in chat [ID:1289011239]
[2023-04-07T20:24:21.046141+0300] [DEBUG] [logging.py:19]  Received callback query [data:"edit_date_30"] from user [ID:1289011239] for message [ID:5238] in chat [ID:1289011239]
[2023-04-07T20:26:07.752221+0300] [DEBUG] [logging.py:11]  Received message [AQID:5243] from user [ID:354866247] in chat [ID:354866247] text "–ù–æ–≤–∞—è –∑–∞–¥–∞—á–∞ üÜï"
[2023-04-07T20:26:09.453004+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:21"] from user [ID:1289011239] for message [ID:5239] in chat [ID:1289011239]
[2023-04-07T20:26:12.625499+0300] [DEBUG] [logging.py:11]  Received message [AQID:5246] from user [ID:354866247] in chat [ID:354866247] text "–∞—ã"
[2023-04-07T20:26:17.072261+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:21"] from user [ID:354866247] for message [ID:5249] in chat [ID:354866247]
[2023-04-07T20:26:24.660398+0300] [DEBUG] [logging.py:11]  Received message [AQID:5254] from user [ID:354866247] in chat [ID:354866247] text "00:36"
[2023-04-07T20:26:26.374590+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:354866247] for message [ID:5255] in chat [ID:354866247]
[2023-04-07T20:26:31.404234+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:354866247] for message [ID:5257] in chat [ID:354866247]
[2023-04-07T20:26:42.567149+0300] [DEBUG] [logging.py:19]  Received callback query [data:"main_menu"] from user [ID:1289011239] for message [ID:5248] in chat [ID:1289011239]
[2023-04-07T20:26:45.963299+0300] [DEBUG] [logging.py:11]  Received message [AQID:5264] from user [ID:1289011239] in chat [ID:1289011239] text "New task üÜï"
[2023-04-07T20:27:00.563700+0300] [DEBUG] [logging.py:19]  Received callback query [data:"main_menu"] from user [ID:1289011239] for message [ID:5235] in chat [ID:1289011239]
[2023-04-07T20:29:49.988191+0300] [DEBUG] [logging.py:11]  Received message [AQID:5267] from user [ID:1289011239] in chat [ID:1289011239] text "New task üÜï"
[2023-04-07T20:29:52.945661+0300] [DEBUG] [logging.py:11]  Received message [AQID:5269] from user [ID:354866247] in chat [ID:354866247] text "–ù–æ–≤–∞—è –∑–∞–¥–∞—á–∞ üÜï"
[2023-04-07T20:29:53.546718+0300] [DEBUG] [logging.py:11]  Received message [AQID:5271] from user [ID:1289011239] in chat [ID:1289011239] text "Jahsh"
[2023-04-07T20:29:55.315960+0300] [DEBUG] [logging.py:11]  Received message [AQID:5273] from user [ID:354866247] in chat [ID:354866247] text "—Ñ—ã–≤"
[2023-04-07T20:29:55.351562+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:21"] from user [ID:1289011239] for message [ID:5272] in chat [ID:1289011239]
[2023-04-07T20:29:57.649508+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:20"] from user [ID:354866247] for message [ID:5274] in chat [ID:354866247]
[2023-04-07T20:30:00.739413+0300] [DEBUG] [logging.py:11]  Received message [AQID:5279] from user [ID:354866247] in chat [ID:354866247] text "—Ñ—ã–≤"
[2023-04-07T20:30:07.061509+0300] [DEBUG] [logging.py:11]  Received message [AQID:5281] from user [ID:1289011239] in chat [ID:1289011239] text "12:00"
[2023-04-07T20:30:08.907650+0300] [DEBUG] [logging.py:11]  Received message [AQID:5283] from user [ID:354866247] in chat [ID:354866247] text "00:23"
[2023-04-07T20:30:09.111879+0300] [DEBUG] [logging.py:19]  Received callback query [data:"yes"] from user [ID:1289011239] for message [ID:5282] in chat [ID:1289011239]
[2023-04-07T20:30:10.443274+0300] [DEBUG] [logging.py:19]  Received callback query [data:"yes"] from user [ID:354866247] for message [ID:5284] in chat [ID:354866247]
[2023-04-07T20:30:12.456435+0300] [DEBUG] [logging.py:11]  Received message [AQID:5287] from user [ID:354866247] in chat [ID:354866247] text "—Ñ—ã–≤"
[2023-04-07T20:30:15.692264+0300] [DEBUG] [logging.py:11]  Received message [AQID:5289] from user [ID:1289011239] in chat [ID:1289011239] text "Hahahhaha"
[2023-04-07T20:30:17.285168+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:354866247] for message [ID:5288] in chat [ID:354866247]
[2023-04-07T20:30:18.942741+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:1289011239] for message [ID:5290] in chat [ID:1289011239]
[2023-04-07T20:30:39.116930+0300] [DEBUG] [logging.py:11]  Received message [AQID:5297] from user [ID:1289011239] in chat [ID:1289011239] text "New task üÜï"
[2023-04-07T20:30:57.059941+0300] [DEBUG] [logging.py:11]  Received message [AQID:5299] from user [ID:354866247] in chat [ID:354866247] text "/edit_task"
[2023-04-07T20:31:00.452623+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_edit_33"] from user [ID:354866247] for message [ID:5301] in chat [ID:354866247]
[2023-04-07T20:31:13.217110+0300] [DEBUG] [logging.py:19]  Received callback query [data:"edit_date_33"] from user [ID:354866247] for message [ID:5302] in chat [ID:354866247]
[2023-04-07T20:31:15.326125+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:7"] from user [ID:354866247] for message [ID:5303] in chat [ID:354866247]
[2023-04-07T20:31:17.108594+0300] [DEBUG] [logging.py:19]  Received callback query [data:"edit_time_33"] from user [ID:354866247] for message [ID:5306] in chat [ID:354866247]
[2023-04-07T20:31:28.065728+0300] [DEBUG] [logging.py:11]  Received message [AQID:5308] from user [ID:354866247] in chat [ID:354866247] text "20:33"
[2023-04-07T20:31:30.523919+0300] [DEBUG] [logging.py:19]  Received callback query [data:"main_menu"] from user [ID:354866247] for message [ID:5310] in chat [ID:354866247]
[2023-04-07T20:31:48.152263+0300] [DEBUG] [logging.py:11]  Received message [AQID:5312] from user [ID:1289011239] in chat [ID:1289011239] text "Tqtqtq"
[2023-04-07T20:31:53.568408+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:24"] from user [ID:1289011239] for message [ID:5313] in chat [ID:1289011239]
[2023-04-07T20:31:59.423631+0300] [DEBUG] [logging.py:11]  Received message [AQID:5318] from user [ID:1289011239] in chat [ID:1289011239] text "12:30"
[2023-04-07T20:32:03.290555+0300] [DEBUG] [logging.py:19]  Received callback query [data:"yes"] from user [ID:1289011239] for message [ID:5319] in chat [ID:1289011239]
[2023-04-07T20:32:11.348035+0300] [DEBUG] [logging.py:11]  Received message [AQID:5321] from user [ID:1289011239] in chat [ID:1289011239] text "no"
[2023-04-07T20:32:13.527884+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no-adding"] from user [ID:1289011239] for message [ID:5322] in chat [ID:1289011239]
[2023-04-07T20:32:24.080412+0300] [DEBUG] [logging.py:11]  Received message [AQID:5326] from user [ID:1289011239] in chat [ID:1289011239] text "/todo"
[2023-04-07T20:32:29.071442+0300] [DEBUG] [logging.py:11]  Received message [AQID:5329] from user [ID:1289011239] in chat [ID:1289011239] text "/edit_task"
[2023-04-07T20:32:31.353606+0300] [DEBUG] [logging.py:19]  Received callback query [data:"task_edit_35"] from user [ID:1289011239] for message [ID:5331] in chat [ID:1289011239]
[2023-04-07T20:33:25.829757+0300] [DEBUG] [logging.py:19]  Received callback query [data:"main_menu"] from user [ID:1289011239] for message [ID:5332] in chat [ID:1289011239]
[2023-04-07T20:33:28.259483+0300] [DEBUG] [logging.py:11]  Received message [AQID:5335] from user [ID:1289011239] in chat [ID:1289011239] text "New task üÜï"
[2023-04-07T20:33:35.267333+0300] [DEBUG] [logging.py:11]  Received message [AQID:5337] from user [ID:1289011239] in chat [ID:1289011239] text "Task"
[2023-04-07T20:33:37.029043+0300] [DEBUG] [logging.py:19]  Received callback query [data:"simple_calendar:DAY:2023:4:21"] from user [ID:1289011239] for message [ID:5338] in chat [ID:1289011239]
[2023-04-07T20:33:43.873266+0300] [DEBUG] [logging.py:11]  Received message [AQID:5341] from user [ID:1289011239] in chat [ID:1289011239] text "12:12"
[2023-04-07T20:33:48.872135+0300] [DEBUG] [logging.py:19]  Received callback query [data:"no"] from user [ID:1289011239] for message [ID:5342] in chat [ID:1289011239]
